// Road Sign Seed Data based on Missouri DOR Highway Sign Recognition Study Sheet
// Source: https://dor.mo.gov/forms/4869.pdf

export const roadSignCategories = [
  {
    name: "Regulatory Signs",
    description: "White/red signs that tell you what you must or must not do",
    orderIndex: 1,
    signs: [
      {
        signName: "Stop Sign",
        signMeaning: "Come to a complete stop. Yield to traffic and pedestrians. Proceed when safe.",
        shape: "Octagon",
        colorScheme: "Red with white letters",
        additionalNotes: "8-sided. Only sign with this shape. Must stop at the stop line if one is present, even if it is located past the stop sign.",
        orderIndex: 1,
      },
      {
        signName: "Yield Sign",
        signMeaning: "Slow down and yield the right-of-way to traffic in the intersection you are crossing or roadway you are entering. Stop if necessary.",
        shape: "Triangle (pointing down)",
        colorScheme: "Red border, white background, red letters",
        additionalNotes: "Only downward-pointing triangle sign.",
        orderIndex: 2,
      },
      {
        signName: "Do Not Enter",
        signMeaning: "You cannot enter this roadway. Turn around.",
        shape: "Square",
        colorScheme: "Red with white lettering",
        additionalNotes: "Typically paired with Wrong Way sign.",
        orderIndex: 3,
      },
      {
        signName: "Wrong Way",
        signMeaning: "You are going the wrong direction. Turn around immediately and safely.",
        shape: "Horizontal rectangle",
        colorScheme: "Red with white lettering",
        additionalNotes: "If you see this, you've entered oncoming traffic lanes.",
        orderIndex: 4,
      },
      {
        signName: "Speed Limit",
        signMeaning: "Maximum legal speed in ideal conditions. Reduce speed in poor conditions.",
        shape: "Vertical rectangle",
        colorScheme: "White with black lettering",
        additionalNotes: "Default Missouri limits: 70 mph rural interstate, 60 mph urban interstate, 25 mph in towns unless posted.",
        orderIndex: 5,
      },
      {
        signName: "No Left Turn",
        signMeaning: "Left turns prohibited at this intersection.",
        shape: "Square",
        colorScheme: "White with black and red symbol",
        additionalNotes: "Red circle with slash over left arrow.",
        orderIndex: 6,
      },
      {
        signName: "No Right Turn",
        signMeaning: "Right turns prohibited at this intersection.",
        shape: "Square",
        colorScheme: "White with black and red symbol",
        additionalNotes: "Red circle with slash over right arrow.",
        orderIndex: 7,
      },
      {
        signName: "No U-Turn",
        signMeaning: "U-turns not allowed at this location.",
        shape: "Square",
        colorScheme: "White with black and red symbol",
        additionalNotes: "Red circle with slash over U-turn arrow.",
        orderIndex: 8,
      },
      {
        signName: "One Way",
        signMeaning: "Traffic flows only in the direction of the arrow.",
        shape: "Horizontal rectangle",
        colorScheme: "Black with white arrow",
        additionalNotes: "Drive only in the direction shown.",
        orderIndex: 9,
      },
      {
        signName: "Keep Right",
        signMeaning: "Pass only on the right side as indicated by the arrow.",
        shape: "Vertical rectangle",
        colorScheme: "White with black arrow",
        additionalNotes: "Typically used around median or obstruction.",
        orderIndex: 10,
      },
      {
        signName: "No Trucks",
        signMeaning: "Trucks are prohibited on this roadway.",
        shape: "Square",
        colorScheme: "White with black and red symbol",
        additionalNotes: "Red circle with slash over truck symbol.",
        orderIndex: 11,
      },
    ],
  },
  {
    name: "Warning Signs",
    description: "Yellow diamond signs that warn of hazards or changes ahead",
    orderIndex: 2,
    signs: [
      {
        signName: "Curve Sign",
        signMeaning: "Road curves ahead in direction shown. Slow down.",
        shape: "Diamond",
        colorScheme: "Yellow with black arrow",
        additionalNotes: "Used to warn of a curve where the recommended speed is less than the posted speed limit for the highway.",
        orderIndex: 1,
      },
      {
        signName: "Right/Left Turn",
        signMeaning: "Sharp turn ahead where recommended speed is 30 mph or less.",
        shape: "Diamond",
        colorScheme: "Yellow with black arrow",
        additionalNotes: "90-degree or sharper turn. More severe than curve sign.",
        orderIndex: 2,
      },
      {
        signName: "Winding Road",
        signMeaning: "Two or more curves in opposite directions. Second may be sharper than first.",
        shape: "Diamond",
        colorScheme: "Yellow with black S-curve",
        additionalNotes: "Also called reverse turn sign. Recommended maximum 30 mph.",
        orderIndex: 3,
      },
      {
        signName: "Merge",
        signMeaning: "Traffic from another road may be entering the road you are on. Be prepared for vehicles to move into your lane.",
        shape: "Diamond",
        colorScheme: "Yellow with black arrows",
        additionalNotes: "Watch for merging vehicles, adjust speed if needed.",
        orderIndex: 4,
      },
      {
        signName: "Lane Ends Merge Left",
        signMeaning: "Two lanes become one. Merge in direction shown.",
        shape: "Diamond",
        colorScheme: "Yellow with black arrows",
        additionalNotes: "If you're in the ending lane, you must yield and merge.",
        orderIndex: 5,
      },
      {
        signName: "Added Lane",
        signMeaning: "Traffic from another road will be entering the road you are on. No merging is necessary because a lane has been added.",
        shape: "Diamond",
        colorScheme: "Yellow with black arrows",
        additionalNotes: "Unlike merge sign, no need to change speed or position.",
        orderIndex: 6,
      },
      {
        signName: "Signal Ahead",
        signMeaning: "There is a traffic light signal ahead on the road you are on. Be ready to stop.",
        shape: "Diamond",
        colorScheme: "Yellow with black traffic light symbol",
        additionalNotes: "Warns of upcoming signal that may not be visible yet.",
        orderIndex: 7,
      },
      {
        signName: "Stop Ahead",
        signMeaning: "Stop sign ahead. Begin slowing down.",
        shape: "Diamond",
        colorScheme: "Yellow with black stop sign symbol",
        additionalNotes: "Prepare to stop at upcoming intersection.",
        orderIndex: 8,
      },
      {
        signName: "Yield Ahead",
        signMeaning: "Yield sign ahead. Prepare to yield or stop.",
        shape: "Diamond",
        colorScheme: "Yellow with black yield sign symbol",
        additionalNotes: "Slow down and prepare to yield right-of-way.",
        orderIndex: 9,
      },
      {
        signName: "Intersection",
        signMeaning: "Another road crosses the road you are on. Watch carefully for traffic crossing your path.",
        shape: "Diamond",
        colorScheme: "Yellow with black cross symbol",
        additionalNotes: "Indicates uncontrolled intersection - no signals.",
        orderIndex: 10,
      },
      {
        signName: "Side Road",
        signMeaning: "Road enters from the direction shown.",
        shape: "Diamond",
        colorScheme: "Yellow with black T-symbol",
        additionalNotes: "Watch for vehicles entering from side.",
        orderIndex: 11,
      },
      {
        signName: "T Intersection",
        signMeaning: "Road you're on ends ahead. You must turn left or right.",
        shape: "Diamond",
        colorScheme: "Yellow with black T",
        additionalNotes: "Prepare to turn - cannot continue straight.",
        orderIndex: 12,
      },
      {
        signName: "Divided Highway Begins",
        signMeaning: "The road will soon become two-way traffic divided by a median or barrier.",
        shape: "Diamond",
        colorScheme: "Yellow with black symbol",
        additionalNotes: "Opposite lanes will be separated.",
        orderIndex: 13,
      },
      {
        signName: "Divided Highway Ends",
        signMeaning: "Divided road ends. Two-way traffic ahead with no median.",
        shape: "Diamond",
        colorScheme: "Yellow with black symbol",
        additionalNotes: "Watch for oncoming traffic - no longer separated.",
        orderIndex: 14,
      },
      {
        signName: "Hill / Steep Grade",
        signMeaning: "Steep downgrade ahead. Use lower gear if needed.",
        shape: "Diamond",
        colorScheme: "Yellow with black truck symbol",
        additionalNotes: "May show percentage of grade. Trucks use low gear.",
        orderIndex: 15,
      },
      {
        signName: "Slippery When Wet",
        signMeaning: "The road ahead becomes unusually slippery in wet weather. Drive carefully in these conditions.",
        shape: "Diamond",
        colorScheme: "Yellow with black car skidding",
        additionalNotes: "Reduce speed and increase following distance in rain.",
        orderIndex: 16,
      },
      {
        signName: "Narrow Bridge",
        signMeaning: "Bridge or road ahead is narrower than current road.",
        shape: "Diamond",
        colorScheme: "Yellow with black bridge symbol",
        additionalNotes: "Slow down, be prepared to meet oncoming traffic.",
        orderIndex: 17,
      },
      {
        signName: "Pedestrian Crossing",
        signMeaning: "Pedestrian crossing ahead. Yield to pedestrians.",
        shape: "Diamond",
        colorScheme: "Yellow with black pedestrian symbol",
        additionalNotes: "Be ready to stop. Especially common near schools.",
        orderIndex: 18,
      },
      {
        signName: "Bicycle Crossing",
        signMeaning: "Bike path crosses road ahead. Yield to cyclists.",
        shape: "Diamond",
        colorScheme: "Yellow with black bicycle symbol",
        additionalNotes: "Watch for bicyclists entering roadway.",
        orderIndex: 19,
      },
      {
        signName: "Deer Crossing",
        signMeaning: "Deer frequently cross road in this area.",
        shape: "Diamond",
        colorScheme: "Yellow with black deer symbol",
        additionalNotes: "Most active at dawn and dusk. Scan road edges.",
        orderIndex: 20,
      },
      {
        signName: "School Crossing",
        signMeaning: "School zone. Watch for children crossing. Slow down.",
        shape: "Pentagon (5-sided)",
        colorScheme: "Yellow with black pedestrian symbols (transitioning to fluorescent yellow-green)",
        additionalNotes: "Unique pentagon shape. This sign is being transitioned to neon green. Reduce speed, heightened awareness.",
        orderIndex: 21,
      },
      {
        signName: "Advisory Speed",
        signMeaning: "Recommended safe speed for the curve or turn.",
        shape: "Square",
        colorScheme: "Yellow with black numbers",
        additionalNotes: "Typically placed below curve/turn warning signs. This is advice for ideal conditions.",
        orderIndex: 22,
      },
      {
        signName: "Large Arrow (Chevron)",
        signMeaning: "Sharp change in direction. Follow arrow direction.",
        shape: "Tall rectangle",
        colorScheme: "Yellow with large black arrow",
        additionalNotes: "Often multiple chevrons outlining a sharp curve.",
        orderIndex: 23,
      },
      {
        signName: "Roundabout Ahead",
        signMeaning: "Roundabout intersection ahead. Slow down and follow posted speed.",
        shape: "Diamond",
        colorScheme: "Yellow with black circular arrows",
        additionalNotes: "Prepare to yield to traffic in circle.",
        orderIndex: 24,
      },
    ],
  },
  {
    name: "Construction/Work Zone Signs",
    description: "Orange signs indicating construction or maintenance work",
    orderIndex: 3,
    signs: [
      {
        signName: "Road Work Ahead",
        signMeaning: "Construction zone ahead. Reduce speed and watch for workers.",
        shape: "Diamond",
        colorScheme: "Fluorescent orange with black lettering",
        additionalNotes: "Fines double in work zones. Speeds typically reduced 10-20 mph.",
        orderIndex: 1,
      },
      {
        signName: "Detour",
        signMeaning: "Road closed ahead. Follow detour in direction shown.",
        shape: "Horizontal rectangle",
        colorScheme: "Orange with black lettering/arrow",
        additionalNotes: "Follow detour signs to return to original route.",
        orderIndex: 2,
      },
      {
        signName: "Lane Closed",
        signMeaning: "Lane ends due to construction. Merge as indicated.",
        shape: "Diamond",
        colorScheme: "Orange with black marking",
        additionalNotes: "Merge early, don't wait until forced.",
        orderIndex: 3,
      },
      {
        signName: "Flagger Ahead",
        signMeaning: "Worker controlling traffic ahead with flag or sign.",
        shape: "Diamond",
        colorScheme: "Orange with black figure",
        additionalNotes: "Obey flagger as you would a traffic signal.",
        orderIndex: 4,
      },
    ],
  },
  {
    name: "Guide Signs",
    description: "Green/blue/brown signs showing directions and services",
    orderIndex: 4,
    signs: [
      {
        signName: "Interstate Highway Marker",
        signMeaning: "Interstate highway number.",
        shape: "Shield with points at top",
        colorScheme: "Red, white and blue",
        additionalNotes: "Even numbers run east-west, odd numbers run north-south.",
        orderIndex: 1,
      },
      {
        signName: "US Route Marker",
        signMeaning: "US highway number.",
        shape: "Shield",
        colorScheme: "Black and white",
        additionalNotes: "Major routes across states.",
        orderIndex: 2,
      },
      {
        signName: "State Route Marker",
        signMeaning: "State highway number.",
        shape: "Circle",
        colorScheme: "Black and white",
        additionalNotes: "Missouri uses white circle with black number.",
        orderIndex: 3,
      },
      {
        signName: "County Route Marker",
        signMeaning: "County road number.",
        shape: "Square",
        colorScheme: "Blue and white",
        additionalNotes: "Lettered roads in Missouri (e.g., Route AA).",
        orderIndex: 4,
      },
      {
        signName: "Exit Sign",
        signMeaning: "Highway exit number and destination.",
        shape: "Horizontal rectangle",
        colorScheme: "Green with white lettering",
        additionalNotes: "Exit numbers match mile markers. Shows upcoming exit.",
        orderIndex: 5,
      },
      {
        signName: "Distance Sign",
        signMeaning: "Shows distance to cities ahead.",
        shape: "Horizontal rectangle",
        colorScheme: "Green with white lettering",
        additionalNotes: "Helps with trip planning.",
        orderIndex: 6,
      },
      {
        signName: "Rest Area",
        signMeaning: "Rest area with facilities ahead.",
        shape: "Square",
        colorScheme: "Blue with white symbols",
        additionalNotes: "May show distance to rest area.",
        orderIndex: 7,
      },
      {
        signName: "Services (Gas/Food/Lodging)",
        signMeaning: "Services available at next exit.",
        shape: "Square",
        colorScheme: "Blue with white symbols",
        additionalNotes: "Shows gas, food, lodging, hospital available.",
        orderIndex: 8,
      },
      {
        signName: "Hospital",
        signMeaning: "Hospital location.",
        shape: "Square",
        colorScheme: "Blue with white H",
        additionalNotes: "Shows direction to medical facility.",
        orderIndex: 9,
      },
      {
        signName: "Park & Recreation",
        signMeaning: "Parks, historic sites, recreational areas.",
        shape: "Horizontal rectangle",
        colorScheme: "Brown with white lettering",
        additionalNotes: "Points to tourist attractions and public recreation.",
        orderIndex: 10,
      },
    ],
  },
  {
    name: "Railroad & Special Signs",
    description: "Signs for railroad crossings and other special situations",
    orderIndex: 5,
    signs: [
      {
        signName: "Railroad Crossing (Advance Warning)",
        signMeaning: "Railroad crossing ahead. Slow down and look for trains. Be prepared to stop.",
        shape: "Circle (round)",
        colorScheme: "Yellow with black X and RR",
        additionalNotes: "Only circular warning sign. The advance warning sign tells you that you are nearing a railroad crossing.",
        orderIndex: 1,
      },
      {
        signName: "Crossbuck",
        signMeaning: "Yield to trains. Treat as yield sign.",
        shape: "X-shape (crossbuck)",
        colorScheme: "White with black 'Railroad Crossing' text",
        additionalNotes: "May have number plate showing how many tracks. Unique X-shape.",
        orderIndex: 2,
      },
      {
        signName: "Railroad Flashing Lights",
        signMeaning: "Train approaching. Stop and wait until lights stop and gate rises.",
        shape: "Circular lights",
        colorScheme: "Red lights that flash alternately",
        additionalNotes: "Stop 15-50 feet from tracks. Wait for lights to stop.",
        orderIndex: 3,
      },
      {
        signName: "Slow Moving Vehicle",
        signMeaning: "Vehicle ahead travels less than 25 mph.",
        shape: "Triangle",
        colorScheme: "Fluorescent orange triangle with red border",
        additionalNotes: "Typically on farm equipment, construction vehicles. Be patient, pass when safe.",
        orderIndex: 4,
      },
      {
        signName: "Soft Shoulder",
        signMeaning: "Shoulder is soft/unpaved. Don't leave pavement.",
        shape: "Diamond",
        colorScheme: "Yellow with black lettering",
        additionalNotes: "If you go off road onto shoulder, you may lose control.",
        orderIndex: 5,
      },
      {
        signName: "Object Marker",
        signMeaning: "Object in roadway or very close to edge (bridge support, guardrail end, etc.)",
        shape: "Diamond or rectangle",
        colorScheme: "Yellow/black diagonal stripes",
        additionalNotes: "Stay in your lane - object is very close or in roadway.",
        orderIndex: 6,
      },
    ],
  },
];

// Road Sign Test Constants
export const ROAD_SIGN_PASSING_SCORE = 80; // 80% to pass
export const ROAD_SIGN_STANDARD_QUESTIONS = 20;
export const ROAD_SIGN_TIME_PER_QUESTION = 30; // seconds for timed mode

