export type QuizQuestionSeed = {
  topic: string
  questionText: string
  optionA: string
  optionB: string
  optionC: string
  optionD: string
  correctAnswer: 'A' | 'B' | 'C' | 'D'
  explanation: string
  chapterReference: string
  sourceUrl: string
  sourceQuote: string
}

const DRIVER_GUIDE = 'https://dor.mo.gov/forms/Driver%20Guide.pdf'

export const quizQuestions: QuizQuestionSeed[] = [
  // --- Rules of the Road ---
  {
    topic: 'Rules of the Road',
    questionText: 'What is the speed limit in any Missouri city, town, or village unless posted otherwise?',
    optionA: '20 mph',
    optionB: '25 mph',
    optionC: '30 mph',
    optionD: '35 mph',
    correctAnswer: 'B',
    explanation: 'Missouri’s default speed limit in any city, town, or village is 25 mph unless a different limit is posted.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'The speed limit in any city, town, or village is 25 mph, unless posted otherwise.',
  },
  {
    topic: 'Rules of the Road',
    questionText: 'When you see a steady yellow traffic light, you should:',
    optionA: 'Speed up to clear the intersection',
    optionB: 'Stop unless you are so close that you cannot stop safely',
    optionC: 'Treat it like a yield sign and keep going',
    optionD: 'Honk and proceed',
    correctAnswer: 'B',
    explanation: 'A steady yellow light means the signal is changing from green to red. Stop unless you are already in the intersection or so close that you cannot stop safely.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Stop for a steady yellow light unless you are within the intersection or are so close that you cannot safely stop before entering the intersection.',
  },
  {
    topic: 'Rules of the Road',
    questionText: 'At a four-way stop, who may proceed first?',
    optionA: 'The driver on the left',
    optionB: 'The driver who arrived first (after a complete stop)',
    optionC: 'The driver going straight',
    optionD: 'The largest vehicle',
    correctAnswer: 'B',
    explanation: 'After coming to a complete stop, the driver who reached the intersection first may go first. If two vehicles arrive at the same time, yield to the driver on your right.',
    chapterReference: 'Missouri Driver Guide, Chapter 4',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'At a four-way stop, the driver reaching the intersection first may proceed before the other drivers (after coming to a complete stop).',
  },
  {
    topic: 'Rules of the Road',
    questionText: 'A solid white line on the right edge of the road typically marks:',
    optionA: 'A lane you may cross to pass',
    optionB: 'The right edge of the roadway',
    optionC: 'A no-parking zone',
    optionD: 'A bicycle-only path',
    correctAnswer: 'B',
    explanation: 'White lines separate traffic moving in the same direction. A solid white line marks the right edge of many roads. Solid lines should not be crossed to pass.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'A solid white line marks the right edge of many roads. Solid Lines should not be crossed in a passing maneuver.',
  },
  {
    topic: 'Rules of the Road',
    questionText: 'When must you use headlights in Missouri?',
    optionA: 'Only after midnight',
    optionB: 'From ½ hour after sunset until ½ hour before sunrise, when you cannot see 500 feet ahead, and when weather requires wipers',
    optionC: 'Only in rain or snow',
    optionD: 'From sunset to sunrise only',
    correctAnswer: 'B',
    explanation: 'Lights are required from a half-hour after sunset to a half-hour before sunrise, whenever persons or vehicles cannot be clearly seen 500 feet ahead, whenever weather requires wipers, and in fog.',
    chapterReference: 'RSMo § 307.020(9); Driver Guide, Chapter 9',
    sourceUrl: 'https://revisor.mo.gov/main/OneSection.aspx?section=307.020',
    sourceQuote: '“When lighted lamps are required” means at any time from a half-hour after sunset to a half-hour before sunrise and at any other time when there is not sufficient light to render clearly discernible persons and vehicles on the highway at a distance of five hundred feet ahead. Lighted lamps shall also be required any time the weather conditions require usage of the motor vehicle’s windshield wipers…',
  },
  {
    topic: 'Rules of the Road',
    questionText: 'According to the Missouri Driver Guide, how should you hold the steering wheel?',
    optionA: '12 and 6 o’clock',
    optionB: '10 and 2 o’clock',
    optionC: 'Left hand between 7 and 9, right hand between 3 and 5',
    optionD: 'One hand at the top of the wheel',
    correctAnswer: 'C',
    explanation: 'The Driver Guide says to place your left hand between 7 and 9 o’clock and your right hand between 3 and 5 o’clock so you can make most turns without taking your hands off the wheel.',
    chapterReference: 'Missouri Driver Guide, Chapter 8',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Place your left hand between the seven & nine o’clock positions and your right hand between the three & five o’clock positions on the steering wheel.',
  },
  {
    topic: 'Rules of the Road',
    questionText: 'What should you do when an emergency vehicle approaches with lights and sirens?',
    optionA: 'Speed up to clear the road',
    optionB: 'Stop wherever you are, even in the intersection',
    optionC: 'Pull to the right edge of the road and stop',
    optionD: 'Continue at normal speed',
    correctAnswer: 'C',
    explanation: 'Pull over to the right and stop until the emergency vehicle has passed. If you are in an intersection, drive through it first, then pull over.',
    chapterReference: 'Missouri Driver Guide, Chapter 4; RSMo § 304.022',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Pull over to the right edge of the road, or as near to the right as possible, when you see or hear an emergency vehicle approaching from any direction. If you are in an intersection, drive through the intersection before you pull over.',
  },
  {
    topic: 'Rules of the Road',
    questionText: 'What is tailgating?',
    optionA: 'Driving too slowly',
    optionB: 'Following another vehicle too closely',
    optionC: 'Blocking an intersection',
    optionD: 'Failing to signal a turn',
    correctAnswer: 'B',
    explanation: 'Tailgating means following too closely. The Driver Guide recommends the three-second rule so you have room to stop if the vehicle ahead stops suddenly.',
    chapterReference: 'Missouri Driver Guide, Chapter 8',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'If you are followed too closely or “tailgated” by another driver, and there is a right lane, move over to the right.',
  },
  {
    topic: 'Rules of the Road',
    questionText: 'When may you pass on the right in Missouri?',
    optionA: 'Never',
    optionB: 'When the vehicle ahead is making a left turn, or on a street/highway with enough unobstructed lanes',
    optionC: 'On any two-lane road',
    optionD: 'Only on rural gravel roads',
    correctAnswer: 'B',
    explanation: 'You may pass on the right when the vehicle ahead is turning left, on a city street with two or more lanes each way, on a one-way street, or on a highway marked for four or more lanes. You may not leave the pavement to pass.',
    chapterReference: 'Missouri Driver Guide, Chapter 4',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'The driver of a motor vehicle may overtake and pass to the right of another vehicle only under the following conditions: When the vehicle overtaken is making or about to make a left turn; Upon a city street with unobstructed pavement of sufficient width for two or more lines of vehicles in each direction; Upon a one-way street; Upon any highway outside of a city with unobstructed pavement of sufficient width and clearly marked for four or more lanes of traffic.',
  },
  {
    topic: 'Rules of the Road',
    questionText: 'A broken yellow center line means:',
    optionA: 'No passing allowed',
    optionB: 'Passing is permitted when it is safe',
    optionC: 'Divided highway ahead',
    optionD: 'Construction zone',
    correctAnswer: 'B',
    explanation: 'Broken lines may be crossed to pass when it is safe. Yellow separates traffic going in opposite directions.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Broken Lines may be crossed in a passing maneuver. Yellow separates traffic traveling in opposite directions.',
  },
  {
    topic: 'Rules of the Road',
    questionText: 'What following-distance method does the Missouri Driver Guide recommend in normal conditions?',
    optionA: '1-second rule',
    optionB: '2-second rule',
    optionC: '3-second rule',
    optionD: '5-second rule',
    correctAnswer: 'C',
    explanation: 'Use the three-second rule: when the vehicle ahead passes a fixed object, you should not reach that object before you finish counting to three.',
    chapterReference: 'Missouri Driver Guide, Chapter 8',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'A good way to measure your safe following distance is to use the “three second rule.”',
  },
  {
    topic: 'Rules of the Road',
    questionText: 'When parking uphill with a curb, which way should your front wheels be turned?',
    optionA: 'Away from the curb (left)',
    optionB: 'Toward the curb (right)',
    optionC: 'Straight ahead',
    optionD: 'It does not matter',
    correctAnswer: 'A',
    explanation: 'Uphill with a curb: turn wheels away from the curb so if the vehicle rolls, the tire catches the curb. Downhill, or any hill with no curb: turn wheels toward the side of the road so the vehicle rolls away from traffic. Missouri’s driving test scores “turning the front wheels in the correct direction for parking” on a hill.',
    chapterReference: 'Missouri Driver Guide, Chapter 2 (hill-parking test) and Chapter 5',
    sourceUrl: 'https://driversed.com/driving-information/driving-techniques/parking-on-a-hill/',
    sourceQuote: 'When headed uphill at a curb, turn the front wheels away from the curb… When headed uphill (or downhill) with no curb, always turn your front wheels to the right so that if your vehicle moves, it will roll off the highway, not into traffic.',
  },
  {
    topic: 'Rules of the Road',
    questionText: 'What does a flashing red traffic light mean?',
    optionA: 'Slow down and keep going',
    optionB: 'Stop, then proceed when safe (same as a stop sign)',
    optionC: 'Yield without stopping',
    optionD: 'Road closed',
    correctAnswer: 'B',
    explanation: 'A flashing red light has the same meaning as a stop sign: come to a full stop, then go when the way is clear.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'A flashing red light means the same thing as a stop sign.',
  },
  {
    topic: 'Rules of the Road',
    questionText: 'You should signal a turn at least how far in advance?',
    optionA: '50 feet',
    optionB: '100 feet',
    optionC: '200 feet',
    optionD: '300 feet',
    correctAnswer: 'B',
    explanation: 'Signal at least 100 feet before you turn so other drivers can be ready.',
    chapterReference: 'Missouri Driver Guide, Chapter 4',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'You should signal at least 100 feet before you turn so the other drivers can be ready.',
  },
  {
    topic: 'Rules of the Road',
    questionText: 'When must you obey a slower speed limit in a school zone?',
    optionA: 'Only on weekdays from 8 to 9 a.m.',
    optionB: 'When lights are flashing or children are present',
    optionC: '24 hours a day, every day',
    optionD: 'Only if a crossing guard is present',
    correctAnswer: 'B',
    explanation: 'Missouri does not set one statewide school-zone speed (such as 20 mph). You must obey the slower posted school-zone limit when lights are flashing or children are present.',
    chapterReference: 'Missouri Driver Guide, Chapter 4',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'You must obey a slower speed limit in a school zone when lights are flashing or children are present.',
  },
  {
    topic: 'Rules of the Road',
    questionText: 'After a complete stop at a red light, when may you turn right?',
    optionA: 'Never — right on red is illegal in Missouri',
    optionB: 'If the way is clear of pedestrians and traffic, unless a “No Right Turn On Red” sign is posted',
    optionC: 'Anytime, without stopping, if no one is in the crosswalk',
    optionD: 'Only between midnight and 6 a.m.',
    correctAnswer: 'B',
    explanation: 'You must stop first. Then you may turn right on red if the way is clear, unless a sign prohibits it.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'After making a complete stop, you may turn right on a red light if the way is clear of pedestrians and traffic. However, you must not turn right on a red light when there is a “No Right Turn On Red” sign posted.',
  },

  // --- Traffic Signs and Signals ---
  {
    topic: 'Traffic Signs and Signals',
    questionText: 'What shape is a typical warning sign?',
    optionA: 'Circle',
    optionB: 'Rectangle',
    optionC: 'Diamond',
    optionD: 'Pentagon',
    correctAnswer: 'C',
    explanation: 'Warning signs are usually diamond-shaped and yellow with black symbols, telling you to slow down and be ready for a hazard.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'These signs are yellow with black lettering or symbols and usually diamond shaped. Diamond = Warning',
  },
  {
    topic: 'Traffic Signs and Signals',
    questionText: 'What does an octagonal (8-sided) sign mean?',
    optionA: 'Yield',
    optionB: 'Stop',
    optionC: 'Railroad crossing',
    optionD: 'No entry',
    correctAnswer: 'B',
    explanation: 'An octagon is used only for stop signs: red with white letters. Come to a full stop.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Octagon = Stop. A stop sign is red with white letters and has eight sides. When you see a stop sign, you must come to a full stop.',
  },
  {
    topic: 'Traffic Signs and Signals',
    questionText: 'A triangular sign with the point down means:',
    optionA: 'Stop',
    optionB: 'Yield',
    optionC: 'School zone',
    optionD: 'No passing',
    correctAnswer: 'B',
    explanation: 'A downward-pointing triangle is a yield sign. Slow down and yield the right-of-way to traffic in the intersection or the road you are entering.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'A yield sign is triangular. It is red and white with red letters. It means you must slow down and yield the right-of-way to traffic in the intersection you are crossing or roadway you are entering.',
  },
  {
    topic: 'Traffic Signs and Signals',
    questionText: 'What color are direction and distance (guide) signs?',
    optionA: 'Blue',
    optionB: 'White',
    optionC: 'Green',
    optionD: 'Brown',
    correctAnswer: 'C',
    explanation: 'Green signs give direction and distance information. Blue is for motorist services; brown is for recreation and cultural sites.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Green = Direction & Distance. Blue = Motorist Services. Brown = Public Recreation & Cultural Interests.',
  },
  {
    topic: 'Traffic Signs and Signals',
    questionText: 'What does a blue sign typically indicate?',
    optionA: 'Recreational area',
    optionB: 'Motorist services (gas, food, lodging, hospital)',
    optionC: 'Construction zone',
    optionD: 'Speed limit',
    correctAnswer: 'B',
    explanation: 'Blue signs mark motorist services such as gas, food, lodging, and hospitals.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Blue = Motorist Services',
  },
  {
    topic: 'Traffic Signs and Signals',
    questionText: 'What does a pentagon-shaped sign indicate?',
    optionA: 'School zone or school crossing',
    optionB: 'State park',
    optionC: 'No entry',
    optionD: 'Hospital ahead',
    correctAnswer: 'A',
    explanation: 'A five-sided pentagon marks a school zone or school crossing. School-related signs are fluorescent yellow-green.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Pentagon = School. Yellow Green = School',
  },
  {
    topic: 'Traffic Signs and Signals',
    questionText: 'What does a “Do Not Enter” sign look like?',
    optionA: 'Red circle with a white X',
    optionB: 'White square with a red circle and a white horizontal bar, reading DO NOT ENTER',
    optionC: 'Red octagon with white letters',
    optionD: 'Yellow diamond with a black X',
    correctAnswer: 'B',
    explanation: 'Do Not Enter is a white square sign with a red circle and a white bar. It means you must not enter that roadway opening.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Do Not Enter — When you see this sign at roadway openings, do not enter this road.',
  },
  {
    topic: 'Traffic Signs and Signals',
    questionText: 'Orange signs are used for:',
    optionA: 'Recreational areas',
    optionB: 'Construction and work zones',
    optionC: 'School zones',
    optionD: 'Railroad crossings',
    correctAnswer: 'B',
    explanation: 'Work-zone signs are fluorescent orange. Speeding or passing in a Missouri work zone can add large extra fines.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Work zone signs are fluorescent orange and indicate some type of work is being performed on or alongside the roadway. Orange = Construction',
  },
  {
    topic: 'Traffic Signs and Signals',
    questionText: 'What does a round yellow sign with an X and “RR” mean?',
    optionA: 'No parking',
    optionB: 'Railroad crossing ahead',
    optionC: 'Wrong way',
    optionD: 'Intersection ahead',
    correctAnswer: 'B',
    explanation: 'The round yellow advance warning sign tells you a railroad crossing is ahead. Slow down, look for a train, and be ready to stop.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'The round advance warning sign tells you that you are nearing a railroad crossing. Round = Railroad',
  },
  {
    topic: 'Traffic Signs and Signals',
    questionText: 'What does a green arrow traffic signal mean?',
    optionA: 'You may proceed with caution against oncoming traffic',
    optionB: 'Protected turn — you may go in the direction of the arrow if the way is clear',
    optionC: 'Turn only after yielding to oncoming traffic',
    optionD: 'The lane is closed',
    correctAnswer: 'B',
    explanation: 'A green arrow is a protected signal: oncoming traffic is stopped. You must still be in the proper lane and the way must be clear of traffic and pedestrians.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'A green arrow tells you that you can drive in the direction the arrow is pointing. You must be in the proper lane and the way must be clear of all traffic and pedestrians. Protected — Vehicles may turn only when they receive a green arrow while opposing vehicles are stopped by a red light.',
  },
  {
    topic: 'Traffic Signs and Signals',
    questionText: 'A white rectangular sign with black text typically indicates:',
    optionA: 'A warning of a hazard ahead',
    optionB: 'A regulatory rule you must follow',
    optionC: 'Services ahead',
    optionD: 'A construction zone',
    correctAnswer: 'B',
    explanation: 'White square or rectangular signs are regulatory: speed limits, lane use, no parking, and other laws.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'White = Regulatory. Many regulatory signs are square- or rectangular-shaped and are white, with black or red letters or symbols.',
  },
  {
    topic: 'Traffic Signs and Signals',
    questionText: 'What does a WRONG WAY sign mean?',
    optionA: 'You made a wrong turn, but there is no immediate danger',
    optionB: 'You have entered a lane of oncoming traffic — pull off, turn around, and go back',
    optionC: 'The road is closed ahead',
    optionD: 'No U-turn allowed',
    correctAnswer: 'B',
    explanation: 'WRONG WAY means you turned into oncoming traffic. Pull off as quickly and safely as you can, turn around, and go back.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Wrong Way — You made a wrong turn and have entered a lane of oncoming traffic. As quickly and safely as possible, pull off the road, turn around and go back.',
  },
  {
    topic: 'Traffic Signs and Signals',
    questionText: 'If a traffic signal is dark or not working, you should treat the intersection as:',
    optionA: 'An uncontrolled intersection — keep going',
    optionB: 'A four-way stop',
    optionC: 'A yield to the left',
    optionD: 'A flashing yellow',
    correctAnswer: 'B',
    explanation: 'Dark or non-working signals operate as a four-way stop. Stop, then proceed when it is your turn and the way is clear.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Dark signals, or traffic signals that aren’t working operate as a four-way stop.',
  },
  {
    topic: 'Traffic Signs and Signals',
    questionText: 'When railroad crossing lights are flashing or the gate is down, you must stop:',
    optionA: 'On the tracks so other drivers see you',
    optionB: 'Within 15 to 50 feet before the railroad tracks',
    optionC: 'At least 200 feet from the tracks',
    optionD: 'Only if you also hear a train',
    correctAnswer: 'B',
    explanation: 'Stop 15 to 50 feet before the tracks. Do not go around the gate. If there are two or more tracks, look for a second train before crossing.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'You must STOP if the red lights are flashing or the gate is down. You must stop within 15 to 50 feet before the railroad tracks. DO NOT try to go around the gate.',
  },

  // --- Safe Driving ---
  {
    topic: 'Safe Driving',
    questionText: 'According to the Missouri Driver Guide, what is the number-one contributing circumstance to traffic crashes in Missouri?',
    optionA: 'Speeding',
    optionB: 'Driver inattention',
    optionC: 'Driving under the influence',
    optionD: 'Running red lights',
    correctAnswer: 'B',
    explanation: 'The Driver Guide states that driver inattention is the number-one contributing circumstance to traffic crashes in Missouri.',
    chapterReference: 'Missouri Driver Guide, back cover',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'The number-one contributing circumstance to traffic crashes in Missouri is driver inattention.',
  },
  {
    topic: 'Safe Driving',
    questionText: 'While your vehicle is in motion on a public road, Missouri law prohibits drivers from:',
    optionA: 'Using hands-free Bluetooth for a voice call',
    optionB: 'Physically holding a cellphone with any part of the body',
    optionC: 'Using voice-to-text',
    optionD: 'Using the phone only for GPS that is mounted in the vehicle',
    correctAnswer: 'B',
    explanation: 'Missouri’s electronic-communication-device law bans holding a phone (or typing/reading messages, recording video, or watching video) while the vehicle is in motion. Hands-free voice calls and mounted GPS are allowed.',
    chapterReference: 'Missouri Driver Guide, Chapter 16; RSMo § 304.822',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'It is against the law for any driver… to use an electronic communication device. Under the new law, while the vehicle is in motion, drivers are prohibited from: Physically holding or supporting a cellphone with any part of their body.',
  },
  {
    topic: 'Safe Driving',
    questionText: 'What should you do if you feel drowsy while driving?',
    optionA: 'Open a window and keep going',
    optionB: 'Turn up the music',
    optionC: 'Pull off the road at a rest stop or safe place and rest',
    optionD: 'Drink coffee and continue without stopping',
    correctAnswer: 'C',
    explanation: 'If you feel sleepy, pull off at the nearest rest stop or service area. A nap is safer than trying to “push through.” Tired drivers can be as dangerous as intoxicated drivers.',
    chapterReference: 'Missouri Driver Guide, Chapter 6',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'When you feel sleepy, pull off the highway at the nearest rest stop or service area. If you are really sleepy, take a nap. Tired drivers are a great danger to themselves, other drivers, and can be as dangerous as intoxicated drivers.',
  },
  {
    topic: 'Safe Driving',
    questionText: 'What is a blind spot?',
    optionA: 'A dirty windshield',
    optionB: 'The space around your vehicle you cannot see in your mirrors',
    optionC: 'Headlight failure',
    optionD: 'A road with no streetlights',
    correctAnswer: 'B',
    explanation: 'Blind spots are the areas mirrors do not cover. Check over your shoulder before changing lanes, and do not linger in another driver’s blind spot.',
    chapterReference: 'Missouri Driver Guide, Chapter 6',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Blind spots are the spaces you cannot see with your rearview mirrors. Do not drive in another vehicle’s blind spot.',
  },
  {
    topic: 'Safe Driving',
    questionText: 'What should you do when merging onto a highway?',
    optionA: 'Always stop at the end of the ramp and wait',
    optionB: 'Use the ramp and acceleration lane to match highway speed, then merge into a gap',
    optionC: 'Merge slowly regardless of traffic speed',
    optionD: 'Honk to force other drivers to let you in',
    correctAnswer: 'B',
    explanation: 'Use the entrance ramp and acceleration lane to match highway speed, signal, and merge into an opening. Do not stop at the end of the acceleration lane unless traffic is so heavy that you have to.',
    chapterReference: 'Missouri Driver Guide, Chapter 6',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Use the ramp and acceleration lane to increase your speed to match the speed of the vehicles on the highway. DO NOT stop at the end of an acceleration lane unless traffic is very heavy and you have to stop.',
  },
  {
    topic: 'Safe Driving',
    questionText: 'If your vehicle breaks down on a highway, what should you do first to warn others?',
    optionA: 'Stand in the travel lane and wave traffic around',
    optionB: 'Get the vehicle off the road if possible and turn on emergency flashers',
    optionC: 'Leave the vehicle in the lane with no lights',
    optionD: 'Walk down the center of the highway for help',
    correctAnswer: 'B',
    explanation: 'Get off the road if you can, turn on emergency flashers, warn other drivers, and never stand in the roadway.',
    chapterReference: 'Missouri Driver Guide, Chapter 6',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'If at all possible, get your vehicle off the road and away from traffic. Turn on your emergency flashers to show you are having trouble. Never stand in the roadway.',
  },
  {
    topic: 'Safe Driving',
    questionText: 'What does “defensive driving” mean in the Missouri Driver Guide?',
    optionA: 'Driving as slowly as possible',
    optionB: 'Expecting other drivers to make mistakes and being ready to react',
    optionC: 'Always yielding, even when you have a green light',
    optionD: 'Using your horn frequently',
    correctAnswer: 'B',
    explanation: 'Defensive driving means keeping your eyes moving, expecting mistakes, and never relying on signs or signals alone to keep others from pulling out in front of you.',
    chapterReference: 'Missouri Driver Guide, Chapter 8',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'To avoid making mistakes, or being in a crash because of someone else’s mistake, you must drive defensively. Expect other drivers to make mistakes, and think what you would do if a mistake does happen.',
  },
  {
    topic: 'Safe Driving',
    questionText: 'On snow or ice, about how much following distance does the Driver Guide recommend?',
    optionA: '3 seconds',
    optionB: '4–5 seconds',
    optionC: '8–10 seconds',
    optionD: '1–2 seconds',
    correctAnswer: 'C',
    explanation: 'Snow and ice greatly increase stopping distance. Leave about eight to ten seconds between you and the vehicle ahead, and brake gently.',
    chapterReference: 'Missouri Driver Guide, Chapter 9',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'It will take longer to stop your vehicle when driving on snow or ice. So be sure to leave a safe distance, about eight to ten seconds, between your vehicle and any vehicle ahead of you.',
  },
  {
    topic: 'Safe Driving',
    questionText: 'What is hydroplaning?',
    optionA: 'Driving through a flooded underpass',
    optionB: 'Tires riding on water instead of the pavement, causing loss of traction',
    optionC: 'Windshield fogging up',
    optionD: 'Engine water damage',
    correctAnswer: 'B',
    explanation: 'Hydroplaning can happen above about 35 mph on wet pavement. Ease off the accelerator; do not hit the brakes hard.',
    chapterReference: 'Missouri Driver Guide, Chapter 9',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'On wet pavement, your tires may ride on the water rather than the pavement. This is known as “hydroplaning” and it refers to loss of traction and control. Hydroplaning can happen at any speed over 35 mph.',
  },
  {
    topic: 'Safe Driving',
    questionText: 'If your vehicle starts to skid, you should:',
    optionA: 'Brake hard immediately',
    optionB: 'Jerk the wheel sharply the other way',
    optionC: 'Take your foot off the accelerator and steer in the direction you want to go (steer into the skid)',
    optionD: 'Accelerate out of it',
    correctAnswer: 'C',
    explanation: 'Take your foot off the gas. Do not slam the brakes. Steer smoothly into the skid — the direction you want the front of the vehicle to go.',
    chapterReference: 'Missouri Driver Guide, Chapter 9',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Handling a skid is the same for front-wheel and rear-wheel drive vehicles. Take your foot off the accelerator, but DO NOT hit the brakes. Gently turn your steering wheel in the direction that your rear wheels are sliding. Steer Into The Skid.',
  },
  {
    topic: 'Safe Driving',
    questionText: 'Why should you avoid driving in another driver’s blind spot?',
    optionA: 'It uses more fuel',
    optionB: 'They may not see you and could change lanes into you',
    optionC: 'It is always illegal',
    optionD: 'It causes extra tire wear',
    correctAnswer: 'B',
    explanation: 'If you stay in a blind spot, the other driver may not know you are there. Pass through quickly without speeding, or drop back so they can see you.',
    chapterReference: 'Missouri Driver Guide, Chapter 6',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Do not drive in another vehicle’s blind spot. When passing another vehicle, get through the other driver’s blind spot as quickly as you can without exceeding the speed limit.',
  },
  {
    topic: 'Safe Driving',
    questionText: 'What does Missouri’s “Move Over” law require when you approach a stationary emergency vehicle with lights on?',
    optionA: 'Stop in your lane until they wave you by',
    optionB: 'Change to a lane not next to them if you can do so safely, or slow down if you cannot',
    optionC: 'Speed up to get past quickly',
    optionD: 'Only apply if the vehicle is a fire truck',
    correctAnswer: 'B',
    explanation: 'On a road with at least two lanes in your direction, move over a lane if it is safe. If you cannot change lanes, slow to a safe speed. This also applies to vehicles showing amber or amber-and-white lights.',
    chapterReference: 'Missouri Driver Guide, back cover; RSMo § 304.022',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Proceed with caution and yield the right-of-way, if possible… by making a lane change into a lane not adjacent to that of the stationary vehicle… or proceed with due caution and reduce the speed of the vehicle… if changing lanes would be unsafe or impossible.',
  },
  {
    topic: 'Safe Driving',
    questionText: 'While driving, the Missouri Driver Guide says you should look:',
    optionA: 'Only at the car directly in front of you',
    optionB: 'Well down the road — not just at the pavement in front of your vehicle',
    optionC: 'Mostly at your phone-mounted GPS',
    optionD: 'Only in your rearview mirror',
    correctAnswer: 'B',
    explanation: 'Look well down the road so you can steer or slow before you reach a problem. Also scan the sides and check mirrors every few seconds.',
    chapterReference: 'Missouri Driver Guide, Chapter 8',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Look well down the road, not just at the road in front of your vehicle. Look for traffic situations where you will need to steer or slow before you get to them.',
  },
  {
    topic: 'Safe Driving',
    questionText: 'If your accelerator gets stuck, the Driver Guide says you should:',
    optionA: 'Turn the ignition to lock while still moving',
    optionB: 'Shift to neutral, apply the brakes, keep your eyes on the road, and look for a way off the road',
    optionC: 'Keep driving and call for help',
    optionD: 'Pump the accelerator',
    correctAnswer: 'B',
    explanation: 'Shift to neutral to cut power to the wheels, brake, warn others, and drive off the road. Turn the key off only after you have stopped — turning it to lock can freeze the steering wheel.',
    chapterReference: 'Missouri Driver Guide, Chapter 9',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Stuck Accelerator: If your accelerator becomes stuck, you should: Shift to neutral; Apply the brakes; Keep your eyes on the road; Look for a way out… When you no longer need to change direction and have stopped, turn off the ignition. (Turning off the key locks the steering wheel of many vehicles.)',
  },
  {
    topic: 'Safe Driving',
    questionText: 'When should you use your hazard (emergency) flashers on the highway?',
    optionA: 'Whenever you are driving below the speed limit',
    optionB: 'When your vehicle is stopped or disabled and you need to warn other drivers',
    optionC: 'In light rain so you are more visible',
    optionD: 'When driving through tunnels',
    correctAnswer: 'B',
    explanation: 'Use emergency flashers for a breakdown, a stop on the shoulder, or another situation where other drivers need to see that you are having trouble.',
    chapterReference: 'Missouri Driver Guide, Chapter 6',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'You can stop on the shoulder of the highway in an emergency. If you do, alert other drivers by turning on your emergency flashers. Turn on your emergency flashers to show you are having trouble.',
  },
  {
    topic: 'Safe Driving',
    questionText: 'What is the correct response when a tire blows out?',
    optionA: 'Brake hard immediately',
    optionB: 'Hold the wheel tightly, ease off the accelerator, and let the vehicle slow before braking gently',
    optionC: 'Swerve onto the shoulder immediately',
    optionD: 'Accelerate to regain control',
    correctAnswer: 'B',
    explanation: 'Grip the wheel, take your foot off the gas, and do not slam the brakes. Slow down, then brake gently when you almost have the vehicle stopped, and pull off the road.',
    chapterReference: 'Missouri Driver Guide, Chapter 9',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Tire Blowout: Hold the steering wheel tightly. Take your foot off the accelerator, but do not hit the brakes. Let your vehicle slow to a stop completely off the road. Apply the brakes when the vehicle is almost stopped.',
  },

  // --- Alcohol, Drugs, and Driving ---
  {
    topic: 'Alcohol, Drugs, and Driving',
    questionText: 'What BAC level can trigger an administrative license action for a driver under 21 in Missouri?',
    optionA: '0.08% or more',
    optionB: '0.04% or more',
    optionC: '0.02% or more',
    optionD: 'Only 0.10% or more',
    correctAnswer: 'C',
    explanation: 'For minors, a BAC of .02% or more can lead to an administrative suspension or revocation. For drivers 21 and older the administrative threshold is .08%.',
    chapterReference: 'Missouri Driver Guide, Chapter 10',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'If your BAC level is .08% or more (or for minors .02% or more), the officer will take your license away and give you a notice.',
  },
  {
    topic: 'Alcohol, Drugs, and Driving',
    questionText: 'How does alcohol affect driving ability?',
    optionA: 'It improves reaction time in small amounts',
    optionB: 'It impairs judgment, vision, and coordination even in small amounts',
    optionC: 'It only affects night vision',
    optionD: 'It has no effect until you feel drunk',
    correctAnswer: 'B',
    explanation: 'Even a small amount of alcohol can affect driving. There is no safe way to drive after drinking.',
    chapterReference: 'Missouri Driver Guide, Chapter 10',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Even a small amount of alcohol may affect your driving ability. If you are going to drink, let someone else drive who has not been drinking.',
  },
  {
    topic: 'Alcohol, Drugs, and Driving',
    questionText: 'What happens if you refuse a chemical test of your BAC after a DWI stop in Missouri?',
    optionA: 'Nothing — testing is always optional with no penalty',
    optionB: 'Your driver license will be taken away for one year',
    optionC: 'You only receive a warning',
    optionD: 'You automatically go to jail for 30 days',
    correctAnswer: 'B',
    explanation: 'Missouri’s implied-consent rule: if you refuse a chemical test, your license is taken for one year. You still may face DWI charges.',
    chapterReference: 'Missouri Driver Guide, Chapter 10',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'If a police officer stops you and you refuse to take a chemical test to determine your BAC, your driver license will be taken away for one year.',
  },
  {
    topic: 'Alcohol, Drugs, and Driving',
    questionText: 'Can prescription medications affect your ability to drive?',
    optionA: 'No — prescriptions are always safe for driving',
    optionB: 'Only illegal drugs affect driving',
    optionC: 'Yes — alcohol, drugs, or even medicine can make you unfit to drive',
    optionD: 'Only in very large doses',
    correctAnswer: 'C',
    explanation: 'The Driver Guide groups alcohol, drugs, and medicine together. Some legal medications cause drowsiness or other effects that make driving unsafe.',
    chapterReference: 'Missouri Driver Guide, Chapter 10',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Driving under the influence of alcohol or drugs, even medicine, or driving when you’re tired can have deadly consequences — for you, your passengers, and other motorists.',
  },
  {
    topic: 'Alcohol, Drugs, and Driving',
    questionText: 'What does DWI stand for in Missouri?',
    optionA: 'Driving While Intoxicated',
    optionB: 'Driving Without Insurance',
    optionC: 'Driving With Impairment',
    optionD: 'Driving While Inexperienced',
    correctAnswer: 'A',
    explanation: 'DWI is Driving While Intoxicated. A court conviction can mean jail, fines, points, and license suspension or revocation.',
    chapterReference: 'Missouri Driver Guide, Chapter 10',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'If you receive a ticket, and a judge finds you guilty of Driving While Intoxicated (DWI) or Blood Alcohol Content (BAC) of .08% or more, you will not be able to legally drive after the ticket is sent to the Department.',
  },
  {
    topic: 'Alcohol, Drugs, and Driving',
    questionText: 'If you have been drinking, the safest option is:',
    optionA: 'Drink coffee before driving',
    optionB: 'Wait 30 minutes then drive',
    optionC: 'Let someone else drive who has not been drinking',
    optionD: 'Drive slowly on back roads',
    correctAnswer: 'C',
    explanation: 'Coffee, cold air, and “waiting a few minutes” do not make you sober. The only safe choice is a sober driver.',
    chapterReference: 'Missouri Driver Guide, Chapter 10',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'If you are going to drink, let someone else drive who has not been drinking. Drinking and driving is not worth the risk to your life and the lives of others.',
  },
  {
    topic: 'Alcohol, Drugs, and Driving',
    questionText: 'What is the BAC level used for adult DWI / administrative action in Missouri?',
    optionA: '0.10%',
    optionB: '0.08%',
    optionC: '0.05%',
    optionD: '0.06%',
    correctAnswer: 'B',
    explanation: 'For drivers 21 and older, .08% BAC is the threshold used for administrative license action and for a BAC/DWI court conviction chart in the Driver Guide.',
    chapterReference: 'Missouri Driver Guide, Chapter 10',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'If your BAC level is .08% or more (or for minors .02% or more), the officer will take your license away and give you a notice. BAC — Driving/operating a vehicle with .08% Blood Alcohol Content or more.',
  },
  {
    topic: 'Alcohol, Drugs, and Driving',
    questionText: 'Which of the following is NOT a listed first-offense DWI court penalty in the Driver Guide?',
    optionA: 'Up to six months in jail',
    optionB: 'A fine of up to $500',
    optionC: 'Improved reaction time after one drink',
    optionD: 'A 90-day license suspension',
    correctAnswer: 'C',
    explanation: 'Alcohol never improves reaction time. A first DWI offense can mean up to six months in jail, a fine up to $500, and a 90-day license suspension.',
    chapterReference: 'Missouri Driver Guide, Chapter 10',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: '1st Offense — Spend up to six months in jail. Pay up to a $500 fine. 1st Offense — 90 day suspension.',
  },
  {
    topic: 'Alcohol, Drugs, and Driving',
    questionText: 'Under Missouri’s Abuse and Lose law, a driver under 21 can lose their license for 90 days for:',
    optionA: 'Any parking ticket',
    optionB: 'An alcohol-related traffic offense, or possessing or using alcohol or drugs while driving',
    optionC: 'Driving 1 mph over the limit',
    optionD: 'Forgetting their insurance card at home',
    correctAnswer: 'B',
    explanation: 'Abuse and Lose targets under-21 drivers for intoxication-related traffic offenses and for possessing or using alcohol or drugs while driving, among other listed offenses.',
    chapterReference: 'Missouri Driver Guide, Chapter 10',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'If you are younger than 21 years of age, your driver license may be taken away for 90 days for any of the following: Any intoxication alcohol-related traffic offense; If you possess or use alcohol or drugs while driving a vehicle…',
  },

  // --- Missouri Driver License Requirements ---
  {
    topic: 'Missouri Driver License Requirements',
    questionText: 'At what age can a Missouri resident apply for an instruction permit?',
    optionA: '14',
    optionB: '15',
    optionC: '16',
    optionD: '17',
    correctAnswer: 'B',
    explanation: 'An instruction permit is available at age 15. It is Step One of Missouri’s Graduated Driver License program.',
    chapterReference: 'Missouri Driver Guide, Chapter 1',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Instruction Permit — Eligible Age: 15. This is the first step in Missouri’s Graduated Driver License Program for young drivers.',
  },
  {
    topic: 'Missouri Driver License Requirements',
    questionText: 'How long must you hold a Missouri instruction permit before an intermediate license?',
    optionA: '30 days',
    optionB: '3 months',
    optionC: 'At least 6 months (182 days)',
    optionD: '1 year',
    correctAnswer: 'C',
    explanation: 'You must hold the instruction permit at least six months (182 days), beginning the day after issuance, and meet the other GDL requirements.',
    chapterReference: 'Missouri Driver Guide, Chapter 1',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'You must… hold the instruction permit for at least six months (182 days) beginning the day after issuance.',
  },
  {
    topic: 'Missouri Driver License Requirements',
    questionText: 'How many hours of supervised driving are required before an intermediate license?',
    optionA: '20 hours',
    optionB: '30 hours',
    optionC: '40 hours, including at least 10 hours at night',
    optionD: '50 hours, all in daylight',
    correctAnswer: 'C',
    explanation: 'A parent, stepparent, legal guardian, or certified trainer must verify 40 hours of driving instruction, including at least 10 hours of nighttime driving.',
    chapterReference: 'Missouri Driver Guide, Chapter 1',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'You must have completed 40 hours of driving instruction with a parent, stepparent, legal guardian, or certified trainer… The required 40 hours must include at least ten hours of nighttime driving.',
  },
  {
    topic: 'Missouri Driver License Requirements',
    questionText: 'When may an intermediate license holder drive alone between 1:00 a.m. and 5:00 a.m.?',
    optionA: 'Anytime — there is no night restriction',
    optionB: 'Never, even with an adult in the car',
    optionC: 'To and from a school activity, job, or an emergency, unless a licensed driver 21 or older is with you',
    optionD: 'Only on weekends',
    correctAnswer: 'C',
    explanation: 'Night driving alone is restricted from 1:00 a.m. to 5:00 a.m., with exceptions for school, work, or an emergency, or when a licensed driver 21 or older is in the vehicle.',
    chapterReference: 'Missouri Driver Guide, Chapter 1',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'You may not drive alone between 1:00 a.m. and 5:00 a.m. except to and from a school activity, job, or an emergency, unless accompanied by a licensed driver 21 years of age or older.',
  },
  {
    topic: 'Missouri Driver License Requirements',
    questionText: 'During the first 6 months of an intermediate license, how many passengers under 19 who are not immediate family may you carry?',
    optionA: 'None',
    optionB: 'One',
    optionC: 'Two',
    optionD: 'No restriction',
    correctAnswer: 'B',
    explanation: 'You may not carry more than one passenger under 19 who is not immediate family. After six months the limit is three such passengers. Immediate family members are not counted in that cap.',
    chapterReference: 'Missouri Driver Guide, Chapter 1',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'During the first six months, you may not operate a motor vehicle with more than one passenger who is under the age of 19 and who is not a member of your immediate family.',
  },
  {
    topic: 'Missouri Driver License Requirements',
    questionText: 'How many questions must you answer correctly to pass the Missouri Class F written test?',
    optionA: '15 of 25 (60%)',
    optionB: '18 of 25 (72%)',
    optionC: '20 of 25 (80%)',
    optionD: '25 of 25 (100%)',
    correctAnswer: 'C',
    explanation: 'The written test has 25 multiple-choice questions from the Driver Guide. You must answer 20 correctly (80%).',
    chapterReference: 'Missouri Driver Guide, introduction and Chapter 2',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'You will need to take a written test of 25 multiple-choice questions… You must correctly answer 20 questions to pass the test. If you are applying for a Class F (operator) license, you must take a 25 question multiple-choice written test.',
  },

  // --- Highway Driving ---
  {
    topic: 'Highway Driving',
    questionText: 'According to the Missouri Driver Guide speed table, what is the maximum speed listed for rural interstates and freeways unless posted otherwise?',
    optionA: '60 mph',
    optionB: '65 mph',
    optionC: '70 mph',
    optionD: '75 mph',
    correctAnswer: 'D',
    explanation: 'The current Driver Guide lists 75 mph as the maximum for rural interstates and freeways. Always obey the posted limit — MoDOT may post a lower speed, especially in urban areas and work zones.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Roadway Maximum Speed — Rural interstates and freeways 75. Use the following guide unless posted speed limits direct otherwise.',
  },
  {
    topic: 'Highway Driving',
    questionText: 'On a highway with two or more lanes in your direction, the left-most lane is intended for:',
    optionA: 'Slower traffic',
    optionB: 'Passing slower vehicles',
    optionC: 'Trucks only',
    optionD: 'Parking',
    correctAnswer: 'B',
    explanation: 'Stay right except to pass. The left-most lane is for passing slower vehicles.',
    chapterReference: 'Missouri Driver Guide, Chapters 6 and 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'On multi-lane roads, the left-most lane is intended to be used to pass slower vehicles. Use the left lane only to pass another vehicle.',
  },
  {
    topic: 'Highway Driving',
    questionText: 'What is the minimum speed you may drive on a Missouri interstate under normal roadway conditions?',
    optionA: '30 mph',
    optionB: '40 mph',
    optionC: '45 mph',
    optionD: 'There is no minimum',
    correctAnswer: 'B',
    explanation: 'You may not drive slower than 40 mph on interstate highways under normal conditions. If that is too fast for you, use another route.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'You may not drive slower than 40 mph on interstate highways under normal roadway conditions.',
  },
  {
    topic: 'Highway Driving',
    questionText: 'When should you reduce speed to leave a highway?',
    optionA: 'While still in the through lanes, well before the exit',
    optionB: 'In the deceleration lane and on the exit ramp',
    optionC: 'Only after you are on local streets',
    optionD: 'You should never slow down for an exit',
    correctAnswer: 'B',
    explanation: 'Get into the proper lane early, then use the deceleration lane and exit ramp to slow down. Obey any speed advisory on the ramp.',
    chapterReference: 'Missouri Driver Guide, Chapter 6',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Use the deceleration lane and the exit ramp to slow down when leaving the highway. Be sure you obey the speed advisory sign on the exit ramp.',
  },
  {
    topic: 'Highway Driving',
    questionText: 'If you miss your highway exit, you should:',
    optionA: 'Stop and back up on the highway',
    optionB: 'Make a U-turn across the median',
    optionC: 'Go to the next exit and come back',
    optionD: 'Cut across the painted gore area',
    correctAnswer: 'C',
    explanation: 'Never stop, back up, or turn around on the highway. Take the next exit and return.',
    chapterReference: 'Missouri Driver Guide, Chapter 6',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'If you miss your exit, DO NOT stop, back up, or try to turn around on the highway. You will have to get off the highway at the next exit and come back to the exit you missed.',
  },

  // --- Parking Regulations ---
  {
    topic: 'Parking Regulations',
    questionText: 'Missouri’s model traffic ordinance prohibits standing or parking within how many feet of a fire hydrant?',
    optionA: '5 feet',
    optionB: '10 feet',
    optionC: '15 feet',
    optionD: '25 feet',
    correctAnswer: 'C',
    explanation: 'RSMo § 300.440 (the model ordinance many cities adopt) bans standing or parking within 15 feet of a fire hydrant. The Driver Guide also lists blocking a hydrant as illegal.',
    chapterReference: 'RSMo § 300.440; Driver Guide, Chapter 5',
    sourceUrl: 'https://revisor.mo.gov/main/OneSection.aspx?section=300.440',
    sourceQuote: 'No person shall… stand or park a vehicle… Within fifteen feet of a fire hydrant.',
  },
  {
    topic: 'Parking Regulations',
    questionText: 'Missouri’s model traffic ordinance prohibits parking within how many feet of a crosswalk at an intersection?',
    optionA: '10 feet',
    optionB: '20 feet',
    optionC: '40 feet',
    optionD: '50 feet',
    correctAnswer: 'B',
    explanation: 'Do not stand or park within 20 feet of a crosswalk at an intersection (model ordinance). The Driver Guide also says not to park in an intersection or on a crosswalk.',
    chapterReference: 'RSMo § 300.440; Driver Guide, Chapter 5',
    sourceUrl: 'https://revisor.mo.gov/main/OneSection.aspx?section=300.440',
    sourceQuote: 'No person shall… stand or park a vehicle… Within twenty feet of a crosswalk at an intersection.',
  },
  {
    topic: 'Parking Regulations',
    questionText: 'When parking downhill, which way should you turn your wheels?',
    optionA: 'Straight ahead',
    optionB: 'Toward the center of the street (into traffic)',
    optionC: 'Toward the side of the road (away from traffic)',
    optionD: 'It does not matter',
    correctAnswer: 'C',
    explanation: 'Turn the wheels sharply toward the side of the road so if the vehicle rolls, it rolls away from traffic — not into the street.',
    chapterReference: 'Missouri Driver Guide, Chapter 5',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'When you park on a hill, turn your wheels sharply towards the side of the road. This way, if your vehicle starts to roll downhill, it will roll away from traffic.',
  },
  {
    topic: 'Parking Regulations',
    questionText: 'What does a yellow-painted curb mean in the Missouri Driver Guide?',
    optionA: 'Handicap parking',
    optionB: 'Short-term paid parking',
    optionC: 'Do not park alongside it',
    optionD: 'Loading zone for any vehicle, any time',
    correctAnswer: 'C',
    explanation: 'The Driver Guide lists “alongside a curb that is painted yellow” as a no-parking location, along with hydrants, driveways, and intersections.',
    chapterReference: 'Missouri Driver Guide, Chapter 5',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Do not park: … Alongside a curb that is painted yellow. … Blocking a fire hydrant. … Across a driveway entrance.',
  },
  {
    topic: 'Parking Regulations',
    questionText: 'Where is it never legal to park, according to the Driver Guide?',
    optionA: 'On a residential street',
    optionB: 'Across a driveway entrance',
    optionC: 'In a parking garage',
    optionD: 'On a cul-de-sac',
    correctAnswer: 'B',
    explanation: 'You may not park across a driveway entrance, in an intersection, on a crosswalk or sidewalk, on a bridge, blocking a hydrant, or facing against traffic.',
    chapterReference: 'Missouri Driver Guide, Chapter 5',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Do not park: In an intersection. On a crosswalk or sidewalk. Across a driveway entrance.',
  },

  // --- Sharing the Road ---
  {
    topic: 'Sharing the Road',
    questionText: 'When passing a bicycle, Missouri law requires you to:',
    optionA: 'Leave 1 foot of space',
    optionB: 'Honk, then pass as close as possible',
    optionC: 'Leave a safe distance and maintain clearance until you are safely past',
    optionD: 'Pass on the sidewalk',
    correctAnswer: 'C',
    explanation: 'State law requires a safe distance when overtaking a bicycle. The Driver Guide adds that you should give bicycles a full lane width and not squeeze past.',
    chapterReference: 'RSMo § 304.678; Driver Guide, Chapter 4',
    sourceUrl: 'https://revisor.mo.gov/main/OneSection.aspx?section=304.678',
    sourceQuote: 'The operator of a motor vehicle overtaking a bicycle proceeding in the same direction on the roadway… shall leave a safe distance, when passing the bicycle, and shall maintain clearance until safely past the overtaken bicycle.',
  },
  {
    topic: 'Sharing the Road',
    questionText: 'When must you stop for a school bus with flashing red lights and a stop arm?',
    optionA: 'Only if you are behind the bus',
    optionB: 'Oncoming and following traffic must stop, except when you are going the opposite way on a divided highway or on a highway with four or more lanes',
    optionC: 'Only if children are visible in the street',
    optionD: 'Only in marked school zones',
    correctAnswer: 'B',
    explanation: 'Stop for the red lights and stop arm from both directions on two-lane roads. You do not have to stop if you are going the opposite direction on a divided highway or on a highway with four or more lanes, or if the bus is in a school loading zone where students do not cross the road.',
    chapterReference: 'Missouri Driver Guide, Chapter 4',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Oncoming and following traffic must stop before they reach the bus when these signals are activated. You do not have to stop: When you are traveling the opposite direction of a school bus on a highway divided by a median…; When you are traveling the opposite direction of a school bus on a highway containing four or more lanes of traffic…',
  },
  {
    topic: 'Sharing the Road',
    questionText: 'When a pedestrian is in a marked or unmarked crosswalk on or approaching your side of the road, you must:',
    optionA: 'Honk so they hurry',
    optionB: 'Speed past before they reach you',
    optionC: 'Yield',
    optionD: 'Drive around them in the next lane',
    correctAnswer: 'C',
    explanation: 'Drivers must yield to pedestrians in a marked or unmarked crosswalk. Even on a green light you must yield to pedestrians still in the intersection.',
    chapterReference: 'Missouri Driver Guide, Chapter 4',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Drivers must yield when a pedestrian is in a marked or unmarked crosswalk on or approaching their side of the road. Even when you are facing a green light you must yield the right-of-way to all pedestrians in the intersection.',
  },
  {
    topic: 'Sharing the Road',
    questionText: 'Before you open a car door on the street side, you should:',
    optionA: 'Open it as fast as possible',
    optionB: 'Check traffic, including bicyclists who often ride near parked cars',
    optionC: 'Rely on your mirrors only',
    optionD: 'Assume bikes will stop',
    correctAnswer: 'B',
    explanation: 'Get out on the curb side if you can. If you must use the street side, check traffic first — including bicyclists — so you do not “door” someone.',
    chapterReference: 'Missouri Driver Guide, Chapter 5',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Check traffic before you open the door. Check for bicyclists, who often travel on the right-hand side of the travel lanes, near parked cars. Check for passing bicyclists before opening your car door into a traffic lane or bicycle lane.',
  },
  {
    topic: 'Sharing the Road',
    questionText: 'Large trucks have “No-Zone” blind spots:',
    optionA: 'Only directly behind them',
    optionB: 'Only on their left side',
    optionC: 'On each side, in the rear, and in the front',
    optionD: 'Only when backing up',
    correctAnswer: 'C',
    explanation: 'Trucks and buses have large No-Zones on both sides, behind, and in front. If you cannot see the driver’s face in the side mirror, they cannot see you.',
    chapterReference: 'Missouri Driver Guide, Chapter 4',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'A truck or bus has blind spots on each side, in the rear and in the front where an automobile cannot be seen. These blind spots are referred to as the “No-Zone.”',
  },
  {
    topic: 'Sharing the Road',
    questionText: 'If a motorcycle is using a lane, you should:',
    optionA: 'Share the same lane to save space',
    optionB: 'Give the motorcyclist the entire lane',
    optionC: 'Pass them with a few inches to spare',
    optionD: 'Follow within one car length',
    correctAnswer: 'B',
    explanation: 'Do not share a lane with a motorcycle. Give a full lane width when passing.',
    chapterReference: 'Missouri Driver Guide, Chapter 4',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'You should not share a lane with a motorcycle. The motorcyclist needs the entire lane for safety reasons. When you are passing, give motorcycles a full lane width.',
  },
  {
    topic: 'Sharing the Road',
    questionText: 'When passing a bicycle or moped, the Driver Guide says you should:',
    optionA: 'Squeeze past in the same lane to keep traffic moving',
    optionB: 'Give a full lane width and wait for a clear stretch if the lane is too narrow to share',
    optionC: 'Pass on the shoulder',
    optionD: 'Drive on the sidewalk to go around',
    correctAnswer: 'B',
    explanation: 'Do not squeeze past a bicycle. Give a full lane and wait for a safe, clear stretch of road if the lane is too narrow to share.',
    chapterReference: 'Missouri Driver Guide, Chapter 4',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'When you are passing, give bicycles and mopeds a full lane width. Do not squeeze past these road users. Wait for a clear stretch of road before passing a cyclist in a lane too narrow to share.',
  },
  {
    topic: 'Sharing the Road',
    questionText: 'When must you dim high beams?',
    optionA: 'Never on rural roads',
    optionB: 'Within 500 feet of an oncoming vehicle, or within 300 feet when following another vehicle',
    optionC: 'Only inside city limits',
    optionD: 'Only if the other driver flashes their lights first',
    correctAnswer: 'B',
    explanation: 'Use low beams within 500 feet of oncoming traffic and within 300 feet when following. The same 500/300-foot rule is in state law.',
    chapterReference: 'Missouri Driver Guide, Chapter 9; RSMo § 307.070',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Use your low beams when you come within 500 feet (about one block) of an oncoming vehicle. Also use your low beams when following another vehicle within 300 feet.',
  },
  {
    topic: 'Sharing the Road',
    questionText: 'When a funeral procession is going through an intersection, other drivers should:',
    optionA: 'Ignore it and follow the traffic signal only',
    optionB: 'Not enter if that would cross the path of the procession; the procession has the right-of-way',
    optionC: 'Yield only to the hearse',
    optionD: 'Join the procession to get through a red light',
    correctAnswer: 'B',
    explanation: 'An organized funeral procession has the right-of-way at intersections regardless of the signal (except for emergency vehicles or a police officer). Do not cut in, join, or pass the procession except where a passing lane is provided.',
    chapterReference: 'Missouri Driver Guide, Chapter 4',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'An organized funeral procession has the right-of-way at all intersections regardless of any traffic control device, except for emergency vehicles or when directed otherwise by law enforcement officials. Do not enter an intersection in which a procession is going through a red signal light, unless you may do so without crossing the path of the funeral procession.',
  },
  {
    topic: 'Sharing the Road',
    questionText: 'Drivers must come to a complete stop for a pedestrian who is:',
    optionA: 'Waiting on the sidewalk with no intent to cross',
    optionB: 'Crossing guided by a dog or carrying a white cane (or white cane with a red tip)',
    optionC: 'Jogging facing traffic on the shoulder',
    optionD: 'Standing at a bus stop',
    correctAnswer: 'B',
    explanation: 'You must always yield to a person who is blind. Stop completely when they are crossing guided by a dog or carrying a white cane.',
    chapterReference: 'Missouri Driver Guide, Chapter 4',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Drivers must always yield the right-of-way to persons who are blind. When a pedestrian is crossing a street or highway guided by a dog or carrying a white cane (or a white cane with a red tip), vehicles must come to a complete stop.',
  },

  // --- Roundabouts ---
  {
    topic: 'Roundabouts',
    questionText: 'When entering a roundabout, you must yield to:',
    optionA: 'Only vehicles exiting the roundabout',
    optionB: 'Traffic already in the circle, plus bicyclists and pedestrians in the crosswalks',
    optionC: 'No one — just enter',
    optionD: 'Only vehicles on your right',
    correctAnswer: 'B',
    explanation: 'Slow down, yield to traffic in the circle and to people in the crosswalks, then enter when there is a gap.',
    chapterReference: 'Missouri Driver Guide, Chapter 4',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'When approaching a roundabout, always yield to traffic in the circle, bicyclists, and pedestrians in the crosswalks. Vehicles within the roundabout have the right of way.',
  },
  {
    topic: 'Roundabouts',
    questionText: 'In a U.S. roundabout, traffic flows:',
    optionA: 'Clockwise',
    optionB: 'Counterclockwise (you make a slight right to enter)',
    optionC: 'Either direction',
    optionD: 'In a figure-eight',
    correctAnswer: 'B',
    explanation: 'You turn slightly right and travel counterclockwise around the center island, then exit at your road.',
    chapterReference: 'Missouri Driver Guide, Chapter 4',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'At a roundabout, drivers who approach the intersection make a slight right turn to go counterclockwise around a circular center island. Always stay to the right of the center island.',
  },
  {
    topic: 'Roundabouts',
    questionText: 'In a multi-lane roundabout, how do you choose a lane?',
    optionA: 'Always use the left lane',
    optionB: 'Always use the right lane',
    optionC: 'Follow roadside signs and pavement markings into the correct lane — and do not change lanes inside the roundabout',
    optionD: 'Change lanes freely inside the circle',
    correctAnswer: 'C',
    explanation: 'Use the lane indicated by signs and arrows. Do not change lanes in the roundabout. If you miss your exit, go around again.',
    chapterReference: 'Missouri Driver Guide, Chapter 4',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'For multi-lane roundabouts, observe roadside signs and pavement markings to direct you into the correct lane. DO NOT change lanes within a roundabout. If you miss your exit, continue through the roundabout until you reach your appropriate exit.',
  },

  // --- Pavement Markings ---
  {
    topic: 'Pavement Markings',
    questionText: 'A double solid yellow center line means:',
    optionA: 'Passing is permitted in both directions',
    optionB: 'You should never cross the two solid yellow lines to pass',
    optionC: 'Passing is permitted when no one is coming',
    optionD: 'The road is one-way',
    correctAnswer: 'B',
    explanation: 'Two solid yellow lines mark the center of a four-lane road (or a no-passing center). Do not cross them to pass.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'The center marking for roads with four lanes consists of two solid yellow lines. You should never cross the two solid yellow lines to pass.',
  },
  {
    topic: 'Pavement Markings',
    questionText: 'What do white arrows painted in a lane mean?',
    optionA: 'Decoration only',
    optionB: 'The direction(s) you may travel from that lane',
    optionC: 'Bicycle lane markings',
    optionD: 'A passing zone',
    correctAnswer: 'B',
    explanation: 'Lane-control signs and pavement arrows tell you which direction you can go from each lane. Dual-use lanes show both a turn arrow and a straight arrow.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'These signs use an arrow symbol to tell you which direction you can go from each lane. Dual-use lanes have both a turn arrow and a straight arrow.',
  },
  {
    topic: 'Pavement Markings',
    questionText: 'A solid yellow line on your side of the center line means:',
    optionA: 'You may pass if you can see far enough',
    optionB: 'Do not pass — it is a no-passing zone',
    optionC: 'The road is ending',
    optionD: 'You must turn left',
    correctAnswer: 'B',
    explanation: 'A solid yellow line on your side marks a no-passing zone, often on hills or curves. Finish passing before you reach it.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'When you see a solid yellow line on your side of the center line, do not try to pass. You must complete passing before you enter the no passing zone.',
  },
  {
    topic: 'Pavement Markings',
    questionText: 'How far may you travel in a two-way left-turn (center) lane?',
    optionA: 'As far as you want',
    optionB: 'No more than 500 feet, and only to prepare for a left turn',
    optionC: 'Only 50 feet',
    optionD: 'You may use it as a travel lane in heavy traffic',
    correctAnswer: 'B',
    explanation: 'Enter the center left-turn lane only to slow or stop before turning left. Do not use it as a through lane, and do not travel in it more than 500 feet.',
    chapterReference: 'Missouri Driver Guide, Chapter 4',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Only enter this lane when preparing to slow down or stop before making a left turn from the main roadway. Do not use this lane as travel lane (a vehicle may not travel in this lane for more than 500 feet).',
  },
  {
    topic: 'Pavement Markings',
    questionText: 'When a sign or signal requires you to stop, where must you stop?',
    optionA: 'Wherever is convenient',
    optionB: 'After you enter the intersection',
    optionC: 'Before the stop line, or before the crosswalk if there is one',
    optionD: 'Only if other cars are present',
    correctAnswer: 'C',
    explanation: 'Stop before the stop line. If there is no stop line, stop before the crosswalk. If there is neither, stop before entering the intersection.',
    chapterReference: 'Missouri Driver Guide, Chapter 7',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'When required to stop because of a sign or signal, you must stop before your vehicle reaches the stop line or, if there is one, the crosswalk. Stop before the stop line. OR stop before the crosswalk. OR if there is no stop line or crosswalk, stop before entering the intersection.',
  },

  // --- Point System and Violations ---
  {
    topic: 'Point System and Violations',
    questionText: 'How many points in 18 months will suspend a Missouri driver license?',
    optionA: '8 points in 18 months',
    optionB: '4 points in 18 months',
    optionC: '12 points in 18 months',
    optionD: '2 points in 18 months',
    correctAnswer: 'A',
    explanation: '8 or more points in 18 months brings a suspension: 30 days the first time, 60 days the second, 90 days the third. 4 points in 12 months only triggers an advisory letter.',
    chapterReference: 'Missouri Driver Guide, Chapter 11',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'If you accumulate a total of 8 or more points in 18 months, your driving privilege will be suspended. 1st suspension — 30 days; 2nd suspension — 60 days; 3rd (or subsequent) suspension — 90 days.',
  },
  {
    topic: 'Point System and Violations',
    questionText: 'How many points does a speeding conviction add in Missouri?',
    optionA: '1 point always',
    optionB: '2 points (municipal/county) or 3 points (state law)',
    optionC: '6 points always',
    optionD: '12 points always',
    correctAnswer: 'B',
    explanation: 'Speeding is 3 points if it is a state-law conviction and 2 points if it is a county or municipal ordinance conviction. The Driver Guide summarizes this as two or three points.',
    chapterReference: 'Missouri Driver Guide, Chapter 11; RSMo § 302.302',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'You may receive two or three points if you are convicted of speeding (depending on if the court was municipal, county, or state level). Speeding . . . 3 points [state-law example].',
  },
  {
    topic: 'Point System and Violations',
    questionText: 'How do points come off your Missouri driving record if you get no new points?',
    optionA: 'They never come off',
    optionB: 'They decrease by 1 point each year',
    optionC: 'After 1 year remaining points drop by one-third; after 2 years by one-half; after 3 years to zero',
    optionD: 'All points reset after 90 days',
    correctAnswer: 'C',
    explanation: 'Points are not removed one-per-year. After one violation-free year remaining points fall by one-third, after two years by one-half, and after three years to zero. Some convictions still stay listed on the record.',
    chapterReference: 'Missouri Driver Guide, Chapter 11',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'After one year - Remaining points will be reduced by one-third. After two years - Remaining points will be reduced by one-half. After three years - Points reduced to zero.',
  },
  {
    topic: 'Point System and Violations',
    questionText: 'What can happen if you fail to keep liability insurance in Missouri?',
    optionA: 'Warning letter only',
    optionB: 'Nothing if you were not in a crash',
    optionC: 'Your driver license and/or license plates may be suspended',
    optionD: 'Only a $5 parking ticket',
    correctAnswer: 'C',
    explanation: 'Missouri requires liability insurance. If the Department learns you did not keep insurance, your license and/or plates can be suspended until you pay the fee and file proof (often an SR-22) for three years.',
    chapterReference: 'Missouri Driver Guide, Chapter 13',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Your driver license and license plates may be taken away or suspended for not having insurance. If the Department learns you have not kept your insurance, you will receive a notice of suspension in the mail.',
  },
  {
    topic: 'Point System and Violations',
    questionText: 'Running a red light (a moving violation not given its own line in the point statute) is assessed how many points?',
    optionA: '0 points',
    optionB: '2 points',
    optionC: '8 points',
    optionD: '12 points',
    correctAnswer: 'B',
    explanation: 'Violations that are not listed with a special point value — including most signal violations — are assessed 2 points. (A municipal stop-sign ticket with no accident is 1 point.)',
    chapterReference: 'RSMo § 302.302(1); DOR Form 899',
    sourceUrl: 'https://revisor.mo.gov/main/OneSection.aspx?section=302.302',
    sourceQuote: 'Any moving violation of a state law or county or municipal or federal traffic ordinance or regulation not listed in this section… 2 points (except any violation of municipal stop sign ordinance where no accident is involved 1 point).',
  },
  {
    topic: 'Point System and Violations',
    questionText: 'What does the Driver Guide list as possible penalties for a first DWI offense?',
    optionA: 'Warning and a $25 fine only',
    optionB: 'Up to 6 months in jail, a fine up to $500, and a 90-day license suspension',
    optionC: 'Community service only',
    optionD: 'A parking ticket',
    correctAnswer: 'B',
    explanation: 'A first DWI can mean up to six months in jail, a fine up to $500, and a 90-day license suspension, plus SATOP, fees, and possible ignition-interlock requirements to reinstate.',
    chapterReference: 'Missouri Driver Guide, Chapter 10',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: '1st Offense — Spend up to six months in jail. Pay up to a $500 fine. 1st Offense — 90 day suspension.',
  },
  {
    topic: 'Point System and Violations',
    questionText: 'How many points is a state-law careless and imprudent driving conviction worth?',
    optionA: '1 point',
    optionB: '2 points',
    optionC: '4 points',
    optionD: '12 points',
    correctAnswer: 'C',
    explanation: 'Missouri uses “careless and imprudent driving,” not a separate everyday “reckless driving” point category. A state-law C&I conviction is 4 points (2 points if it is only a municipal/county ordinance).',
    chapterReference: 'Missouri Driver Guide, Chapter 11; RSMo § 302.302',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Careless & Imprudent Driving . . . 4 points',
  },
  {
    topic: 'Point System and Violations',
    questionText: 'What happens if you accumulate 12 or more points in 12 months in Missouri?',
    optionA: 'A warning letter only',
    optionB: 'A 30-day suspension',
    optionC: 'A 1-year revocation of your driving privilege',
    optionD: 'Permanent loss of your license with no way to reapply',
    correctAnswer: 'C',
    explanation: 'Your privilege is revoked for one year if you accumulate 12 points in 12 months, 18 in 24 months, or 24 in 36 months.',
    chapterReference: 'Missouri Driver Guide, Chapter 11',
    sourceUrl: DRIVER_GUIDE,
    sourceQuote: 'Your driving privilege will be revoked for one year if you accumulate: 12 or more points in 12 months; 18 or more points in 24 months; 24 or more points in 36 months.',
  },

  // --- Hand Signals ---
  {
    topic: 'Hand Signals',
    questionText: 'What does it mean when a driver extends their left arm straight out the window?',
    optionA: 'Slowing down',
    optionB: 'Right turn',
    optionC: 'Left turn',
    optionD: 'Stop for a school bus',
    correctAnswer: 'C',
    explanation: 'Left arm straight out = left turn. You may signal with your arm or with the vehicle’s turn signals.',
    chapterReference: 'RSMo § 304.019; Driver Guide, Chapter 4',
    sourceUrl: 'https://revisor.mo.gov/main/OneSection.aspx?section=304.019',
    sourceQuote: 'For a left turn the hand and arm shall be extended horizontally; for a right turn the hand and arm shall be extended upward; and to stop or slow the vehicle, the hand and arm shall be extended downward.',
  },
  {
    topic: 'Hand Signals',
    questionText: 'What does it mean when a driver extends their left arm upward at a 90-degree angle?',
    optionA: 'Left turn',
    optionB: 'Right turn',
    optionC: 'Slowing down only (not a turn)',
    optionD: 'Pass me',
    correctAnswer: 'B',
    explanation: 'Left arm bent up at the elbow (hand pointing up) is the hand signal for a right turn.',
    chapterReference: 'Missouri Driver Guide, Chapter 4; RSMo § 304.019',
    sourceUrl: 'https://revisor.mo.gov/main/OneSection.aspx?section=304.019',
    sourceQuote: 'For a left turn the hand and arm shall be extended horizontally; for a right turn the hand and arm shall be extended upward; and to stop or slow the vehicle, the hand and arm shall be extended downward.',
  },
  {
    topic: 'Hand Signals',
    questionText: 'What does it mean when a driver extends their left arm downward at a 90-degree angle?',
    optionA: 'Left turn',
    optionB: 'Right turn',
    optionC: 'Slowing or stopping',
    optionD: 'Hazard warning',
    correctAnswer: 'C',
    explanation: 'Left arm bent down (hand pointing down) means the driver is slowing or stopping.',
    chapterReference: 'RSMo § 304.019; Driver Guide, Chapter 4',
    sourceUrl: 'https://revisor.mo.gov/main/OneSection.aspx?section=304.019',
    sourceQuote: '…to stop or slow the vehicle, the hand and arm shall be extended downward.',
  },
]

export const QUIZ_TOPIC_COUNTS: Record<string, number> = quizQuestions.reduce(
  (counts, q) => {
    counts[q.topic] = (counts[q.topic] ?? 0) + 1
    return counts
  },
  {} as Record<string, number>,
)
