export type TrainingSkill = {
  title: string
  description: string
  teachingNotes: string
}

export type TrainingPhase = {
  orderIndex: number
  title: string
  description: string
  skills: TrainingSkill[]
}

export const trainingPhases: TrainingPhase[] = [
  {
    orderIndex: 1,
    title: 'Basic Safety & Vehicle Familiarity',
    description: 'Master these before the car moves',
    skills: [
      { title: 'Adjust seat position', description: 'Reach pedals comfortably, see over steering wheel', teachingNotes: 'Sit so you can press the brake all the way with a slight bend still in your knee, and see the road over the wheel without stretching. If you have to scoot forward or crane your neck, you are not set. Mastery feels planted and in control before the engine starts.' },
      { title: 'Adjust all mirrors', description: 'Rearview and both side mirrors', teachingNotes: 'Set the inside mirror to fill with the rear window, then angle the sides so you just barely see your own rear fender. You should not hunt for a car behind you. When this is mastered, a quick glance tells you who is there and who is not.' },
      { title: 'Check seatbelt fits properly', description: 'Across chest and hips', teachingNotes: 'The lap belt belongs low across your hips, not your stomach, and the shoulder belt across your chest away from your neck. Click it before you touch the shifter. Mastery means you never roll an inch unbelted, and you notice immediately if a passenger is not buckled.' },
      { title: 'Locate and test turn signals, hazard lights, wipers', description: 'Know location without looking', teachingNotes: 'Find the signal stalk, hazards, and wipers with your eyes on the windshield. Click left, right, hazards, and wipe once so you know they work. Mastery is being able to signal or clear the glass in traffic without looking down at the controls.' },
      { title: 'Find parking brake location and operation', description: 'Engage and release smoothly', teachingNotes: 'Know exactly where the parking brake is and how it feels when it is fully set and fully released. Use it every time you park, then confirm the car does not roll. Mastery is a smooth set and release with no surprise lurch when you start moving.' },
      { title: 'Identify gas, brake pedals', description: 'Know pedal positions by feel', teachingNotes: 'Cover the brake with your right foot and find the gas beside it without looking. Your left foot stays on the dead pedal. Mastery means you never press the wrong pedal, even when you are startled, because your feet already know the layout.' },
      { title: 'Check that doors are properly closed', description: 'All doors secure before moving', teachingNotes: 'Listen for a solid latch and glance at the door-ajar light before you shift out of Park. If a door is cracked, stop and close it — do not drive with it. Mastery is a quick, automatic check every time someone gets in or out.' },
      { title: 'Start and turn off engine safely', description: 'Proper startup sequence', teachingNotes: 'Foot on the brake, gear in Park, then start. When you shut down, stop fully, shift to Park, set the brake, then turn it off. Mastery is the same calm sequence every time — never reaching for the key while the car is still rolling.' },
      { title: 'Understand gear selector (P-R-N-D)', description: 'Park, Reverse, Neutral, Drive', teachingNotes: 'Park locks the transmission, Reverse backs you up, Neutral frees the wheels, Drive moves you forward. Come to a complete stop before you change between Drive and Reverse. Mastery is choosing the right gear without looking down and never forcing the shifter.' },
      { title: 'Operate windshield wipers and lights', description: 'All wiper speeds, headlights, high beams', teachingNotes: 'Know off, intermittent, low, high, and wash by feel. Headlights on at dusk or in rain; high beams only when no one is ahead or oncoming. Mastery is matching wipers and lights to conditions in a second, without taking your attention off the road.' },
      { title: 'Locate and use horn', description: 'Appropriate horn use situations', teachingNotes: 'The horn is a warning, not a scolding. Use a short tap to alert someone who does not see you — a pedestrian stepping out, a car drifting. Mastery is using it early and briefly, then staying ready to brake. Never hold it in anger.' },
      { title: 'Understand dashboard warning lights', description: 'Identify critical warning indicators', teachingNotes: 'Know the red lights that mean stop soon — oil, brake, temperature — versus yellow lights that mean get it checked. If a red warning appears while you drive, find a safe place to pull over. Mastery is reading the cluster at a glance and reacting, not ignoring it.' },
      { title: 'Check fuel level and understand gauges', description: 'Read fuel, temperature, and other gauges', teachingNotes: 'Check fuel before you leave, not when the light is already on. Know a normal temperature range and what the speedometer and tach are telling you. Mastery is a ten-second pre-drive glance that confirms you have fuel, a healthy engine, and no surprises.' },
    ],
  },
  {
    orderIndex: 2,
    title: 'Fundamental Driving Skills',
    description: 'Empty parking lot practice',
    skills: [
      { title: 'Smooth starts from complete stop', description: 'Gradual, controlled acceleration', teachingNotes: 'Release the brake, then roll into the gas so the car eases forward with no lurch or stall of speed. Keep your eyes up, not on the hood. Mastery is a start so smooth a passenger would not spill a drink, every time, from a dead stop.' },
      { title: 'Progressive braking to smooth stops', description: 'No jerking, stops before the line', teachingNotes: 'Brake early and steadily, then ease off just before you stop so the nose does not dive. Plan to stop before the line, not on it. Mastery is a controlled stop that looks planned from fifty feet away — no last-second stab at the pedal.' },
      { title: 'Straight line driving at consistent speed', description: 'Maintain lane position', teachingNotes: 'Pick a speed and hold it with small gas and brake changes. Keep the car centered using the lane lines, not the car in front of you. Mastery is a quiet, straight track with almost no steering wiggle and a steady speed you chose on purpose.' },
      { title: 'Gentle steering inputs and corrections', description: 'Small corrections, no overcorrecting', teachingNotes: 'Steer with quiet hands at 9 and 3. If you drift, a small correction is enough — chasing the wheel makes it worse. Mastery looks boring: the car stays centered because you make tiny fixes early, not big swings late.' },
      { title: 'Proper following distance judgment (3-second rule)', description: 'Maintain safe distance', teachingNotes: 'When the car ahead passes a landmark, count three seconds before you reach it. Add time in rain, at night, or behind trucks. Mastery is holding that space without being told, and dropping back on your own when someone cuts in.' },
      { title: 'Forward parking between lines', description: 'Center in space, wheels straight', teachingNotes: 'Enter slowly, center the car between the lines, and stop with wheels straight and enough room to open doors. If you are crooked, pull out and reset — that is the skilled move. Mastery is a centered park on the first or second try without hanging over a line.' },
      { title: 'Reverse parking (backing into space)', description: 'Use mirrors and backup camera', teachingNotes: 'Go slow enough that you can stop instantly. Use mirrors first, camera as a helper, and turn your head before you start. Mastery is backing into the space on a controlled path, centered, without tapping a curb or neighboring car.' },
      { title: 'Parallel parking basics', description: 'Reference points and timing', teachingNotes: 'Line up, reverse slowly, and use your reference points to swing the rear in, then the front, without hitting the curb. Speed is the enemy — crawl. Mastery is a calm park within a reasonable gap, wheels straight, and a clean pull-out afterward.' },
      { title: 'Angle parking (45-degree spaces)', description: 'Enter and exit safely', teachingNotes: 'Signal, pick your space early, and turn in at a speed you can stop. When you leave, creep out until you can see past the parked cars, then go. Mastery is entering centered and exiting without forcing someone to slam on their brakes.' },
      { title: 'Three-point turn', description: 'Safe execution in tight space', teachingNotes: 'Signal, check all around, then turn across, reverse with another look, and pull through. Each leg is a complete stop and a new scan. Mastery is a tight, legal turn that never surprises a car coming the other way because you looked first every time.' },
      { title: 'Backing in straight line', description: 'Check mirrors, slow and controlled', teachingNotes: 'Look back over your shoulder, then use mirrors to keep the car straight. Crawl. If you drift, stop and straighten instead of cranking the wheel at speed. Mastery is a straight, slow reverse that you could stop in a foot if a person appeared.' },
    ],
  },
  {
    orderIndex: 3,
    title: 'Traffic Navigation',
    description: 'Quiet residential streets',
    skills: [
      { title: 'Right turns at intersections', description: 'Signal, check, turn from correct lane', teachingNotes: 'Signal early, stay in the rightmost lane, check mirrors and the crosswalk, then turn into the nearest lane. Slow enough that a pedestrian could still cross. Mastery is a legal, square right turn with no wide swing and no surprise for people on the corner.' },
      { title: 'Left turns at intersections', description: 'Yield oncoming traffic, proper lane', teachingNotes: 'Signal, enter the intersection only when you have a plan to wait, and yield to oncoming traffic and pedestrians. Turn into the correct lane, not the far one. Mastery is patience plus a committed turn when the gap is real — never creeping into someone else\'s path.' },
      { title: 'Stop sign procedure', description: 'Full stop, check all directions, proceed', teachingNotes: 'Come to a complete stop behind the line. Look left, right, left again, then go when it is clear — not a rolling pause. Mastery is a true stop every time, even on empty streets, with your wheels pointed where you intend to go.' },
      { title: 'Yield sign procedure', description: 'Slow, assess traffic, merge safely', teachingNotes: 'Slow enough that you can stop if you must. If someone is already there, they go first. Merge only into a gap you would want someone else to take. Mastery is arriving at a yield already decided: stop, or roll through because it is truly clear.' },
      { title: 'Traffic light responses', description: 'Green, yellow, red — proper responses', teachingNotes: 'Green means go if the intersection is clear. Yellow means stop if you can do it safely — do not race it. Red is a full stop. Mastery is reading the light early, covering the brake, and never being the car that sneaks through on red.' },
      { title: 'Lane changes on surface streets', description: 'Signal, mirror, blind spot, move', teachingNotes: 'Signal, check mirror, turn your head to the blind spot, then move if it is clear. Do not drift while you look. Mastery is a lane change that other drivers can predict, completed in one smooth motion with space on both sides when you arrive.' },
      { title: 'Proper speed for residential areas', description: 'Typically 25 mph, watch for children', teachingNotes: 'Missouri residential streets are usually 25 unless posted. Slow more near parked cars, balls, and driveways — a child can appear in a second. Mastery is choosing a speed that matches what you can see, not just the number on the sign.' },
      { title: 'Pedestrian right-of-way', description: 'Crosswalks, driveways, school zones', teachingNotes: 'If a person is in a crosswalk or stepping toward one, you stop. Watch driveways and school zones as if someone will walk out, because they will. Mastery is yielding early enough that a pedestrian never has to hesitate or hurry because of you.' },
      { title: 'Navigating 4-way stops', description: 'Right-of-way order, communication', teachingNotes: 'First to arrive goes first. If you arrive together, yield to the right. Make eye contact and be obvious with your intention. Mastery is a calm, legal order — no extra waves that confuse people, and no creeping into the middle out of impatience.' },
      { title: 'U-turns where legal', description: 'Check signs, traffic, execute safely', teachingNotes: 'Confirm it is legal, that you have room, and that oncoming traffic is far enough away. Signal, turn in one smooth arc, and do not cut the corner. Mastery is choosing not to U-turn when it is tight or rushed — that judgment is part of the skill.' },
      { title: 'Driveway entry and exit', description: 'Check pedestrians and traffic', teachingNotes: 'When you leave a driveway, stop and look both ways for people on the sidewalk first, then cars. Enter slowly so you can stop short of anyone walking. Mastery is treating every driveway like an intersection, not a private shortcut onto the street.' },
    ],
  },
  {
    orderIndex: 4,
    title: 'Intermediate Traffic Skills',
    description: 'Busier streets and multi-lane roads',
    skills: [
      { title: 'Multi-lane road navigation', description: 'Choose correct lane, maintain position', teachingNotes: 'Pick the lane for where you are going next, then stay centered in it. Do not wander across lines or camp in a turn-only lane by accident. Mastery is planning a lane early, holding it, and changing only with a signal and a real reason.' },
      { title: 'Left turn from center turn lane', description: 'Enter and exit correctly', teachingNotes: 'Enter the two-way left-turn lane only when you are ready to turn, wait for a gap, then complete the turn. Do not use it as a travel lane. Mastery is a short, legal wait in the center, then a committed turn that does not block through traffic longer than needed.' },
      { title: 'Right turn on red', description: 'Full stop, check, go when safe', teachingNotes: 'Full stop first, even if the road looks empty. Check left for cars, the crosswalk for people, then turn if it is allowed and clear. Mastery is never rolling through a right on red, and knowing when a sign says you must wait for green.' },
      { title: 'Protected left turn signal', description: 'Green arrow — turn efficiently', teachingNotes: 'A green arrow means oncoming traffic should be stopped — still glance, then turn without delay so you do not burn the arrow. Stay in your lane through the turn. Mastery is a prompt, legal protected left that is moving as soon as it is safe, not after the arrow dies.' },
      { title: 'Unprotected left turn', description: 'Yield, gap judgment, turn safely', teachingNotes: 'You turn only when the oncoming gap is big enough to finish without rushing anyone. Wheels stay straight while you wait so a rear-end does not push you into traffic. Mastery is saying “not yet” more often than you go, then turning once with commitment.' },
      { title: 'Roundabout navigation', description: 'Yield to traffic, enter, exit correct lane', teachingNotes: 'Slow, yield to cars already in the circle, then enter when there is a gap. Stay in your lane and signal as you exit. Mastery is a smooth yield-and-go with no stop in the circle and no last-second lane hop to catch an exit.' },
      { title: 'School zone awareness', description: 'Speed, zones, bus protocols', teachingNotes: 'When children are present, Missouri school zones are typically 20 mph. Watch for the pentagon signs, crossing guards, and buses with lights. Mastery is already slow before the first cone, and a full stop for a bus with flashing reds unless a median divides the road.' },
      { title: 'Railroad crossing procedure', description: 'Stop, look, listen, cross safely', teachingNotes: 'Slow, look both ways, and never race a gate. If lights flash or a train is near, stop well back. Cross without shifting or stopping on the tracks. Mastery is treating every crossing as active until you have seen it is clear — trains always win.' },
      { title: 'Emergency vehicle response', description: 'Pull right, stop, yield', teachingNotes: 'Sirens or lights: signal, pull to the right, and stop until they pass. Do not block an intersection. Mastery is hearing them early, finding a hole on the right, and staying put — no following the fire truck or crowding the ambulance.' },
      { title: 'Construction zone driving', description: 'Reduce speed, follow signs, workers present', teachingNotes: 'Orange signs are the law in that zone. Slow down, expect sudden lane shifts, and give workers a wide buffer. Mastery is patience: you arrive a minute later instead of squeezing by a person in a vest at full speed.' },
    ],
  },
  {
    orderIndex: 5,
    title: 'Highway and Freeway Driving',
    description: 'High-speed, multi-lane traffic',
    skills: [
      { title: 'On-ramp acceleration and merging', description: 'Match speed, find gap, merge smoothly', teachingNotes: 'Use the ramp to get to highway speed. Signal, find a gap, and merge without stopping at the end unless traffic forces it. Mastery is arriving beside traffic already matching their speed, then sliding in so no one has to slam the brakes for you.' },
      { title: 'Highway lane maintenance', description: 'Stay centered, consistent speed', teachingNotes: 'Pick a lane, stay in the middle of it, and hold a steady speed. Small steering is enough at 70. Mastery looks calm: you are not ping-ponging between lines or constantly changing speed with every dip in the pack.' },
      { title: 'Highway speed judgment', description: 'Posted limits, flow of traffic', teachingNotes: 'Obey the posted limit — rural Missouri interstates are often 70 — and avoid both crawling and weaving through packs. If traffic is slower than the limit, match a safe flow in the right lanes. Mastery is a legal speed you can justify, not whatever the fastest car is doing.' },
      { title: 'Following distance at highway speeds', description: '3-4 second rule minimum', teachingNotes: 'At highway speed you need at least three to four seconds to the car ahead, more in rain or at night. If someone cuts in, drop back again. Mastery is space you protect on purpose, because stopping from 70 takes far more road than it feels like.' },
      { title: 'Lane changes on highway', description: 'Signal, mirror, blind spot check', teachingNotes: 'Signal early, check mirrors, turn your head, then move into a gap that is already there. Do not squeeze. Mastery is a highway lane change that looks planned from behind — other drivers had time to see you and you never occupied someone\'s blind spot for long.' },
      { title: 'Passing other vehicles', description: 'When legal, safely execute', teachingNotes: 'Pass on the left when it is legal and you can complete it without lingering. Signal, move, clear the vehicle, then return. Mastery is a pass that is decisive and brief — you do not hover beside a truck or dive back in the second you are even with their bumper.' },
      { title: 'Exit ramp procedure', description: 'Signal early, reduce speed on ramp', teachingNotes: 'Get in the exit lane early, signal, and keep highway speed until you are on the ramp, then slow. Braking hard on the freeway to make an exit is the mistake. Mastery is being in position a half mile early and leaving the mainline without surprising anyone.' },
      { title: 'Dealing with large trucks', description: 'Blind spots, safe following distance', teachingNotes: 'Large trucks present hazardous situations because they are difficult to stop and are hard to drive. You must be aware of your position so you may be seen in the driver\'s mirrors and be able to react if they suddenly change lanes or have an emergency.' },
      { title: 'Highway driving at night', description: 'Headlights, following distance, fatigue', teachingNotes: 'Headlights on, high beams only when the road is empty of other cars. Add following distance and watch for deer at the edges. Mastery is slowing your night a little on purpose — if you feel heavy-eyed, you exit and rest instead of “pushing through.”' },
      { title: 'Interstate interchange navigation', description: 'Multi-level, following signs', teachingNotes: 'Read signs early, pick the lane the sign tells you, and commit. Last-second cuts across gore stripes cause wrecks. Mastery is being in the correct lane before the split, even if that means missing an exit and taking the next one safely.' },
    ],
  },
  {
    orderIndex: 6,
    title: 'Challenging Conditions',
    description: 'Weather and visibility challenges',
    skills: [
      { title: 'Rain driving', description: 'Reduce speed, increase following distance', teachingNotes: 'Slow down, turn headlights on, and give yourself extra seconds behind the car ahead. First rain after a dry spell is the slickest. Mastery is a quieter, slower version of your normal drive — no sudden steering or braking that would break traction.' },
      { title: 'Wet road braking distances', description: 'Stop earlier, avoid sudden braking', teachingNotes: 'On wet pavement you need more road to stop, so you brake earlier and smoother. If the wheels start to slide, ease off and reapply. Mastery is stopping with room to spare because you planned the stop farther back than you would on a dry day.' },
      { title: 'Fog driving', description: 'Low beams, slower speeds, more space', teachingNotes: 'Low beams only — high beams bounce back at you. Slow to what you can actually see, and increase space. Mastery is being willing to pull off if you cannot see far enough to stop, instead of guessing what is in the gray.' },
      { title: 'Bright sunlight and glare', description: 'Sun visors, sunglasses, slow down', teachingNotes: 'Use the visor and sunglasses, and slow down when the sun is sitting on the windshield. Watch for pedestrians you might not see. Mastery is not driving into a wall of glare at full speed — you reduce speed until you can see the lights and the road again.' },
      { title: 'Night driving skills', description: 'Use headlights, watch for pedestrians', teachingNotes: 'Use headlights from sunset to sunrise, dim for oncoming cars, and scan beyond your beams for people and animals. Fatigue makes night harder. Mastery is a slower scan, earlier brakes, and the humility to go home if you cannot keep your eyes sharp.' },
      { title: 'Gravel or unpaved roads', description: 'Slower speeds, wider turns', teachingNotes: 'Slow before the gravel, not after you start sliding. Steer gently and give yourself a wider path through turns. Mastery is a controlled crawl that does not throw rocks or lose the rear end because you treated dirt like pavement.' },
      { title: 'Road construction detours', description: 'Follow signs, watch for changes', teachingNotes: 'Follow the orange sequence even if your GPS argues. Expect lanes to end, workers to step out, and the pavement to change. Mastery is staying in the marked path and letting the rushed driver go around you rather than inventing your own shortcut through cones.' },
      { title: 'Tire blowout response', description: 'Grip wheel, ease off gas, steer straight', teachingNotes: 'Both hands on the wheel, ease off the gas, and steer straight. Do not slam the brakes or jerk toward the shoulder. Mastery is riding it down in a straight line to a safe stop, then turning on hazards — panic swerves are what put you into other lanes.' },
      { title: 'Brake failure response', description: 'Downshift, pump brakes, use parking brake', teachingNotes: 'Pump the pedal, downshift to let the engine slow you, then ease the parking brake while you steer to a safe place. Do not shut the car off while it is moving. Mastery is a practiced calm: you still have options, and you use them in order instead of freezing.' },
      { title: 'Driving in heavy traffic', description: 'Patience, space management, no aggression', teachingNotes: 'Leave a gap, cover the brake, and let gaps close without racing them. Aggressive driving in a jam only creates new hazards. Mastery is arriving later but intact — you protect your space and ignore the honks behind you.' },
    ],
  },
  {
    orderIndex: 7,
    title: 'Advanced Safety and Emergency Skills',
    description: 'Defensive driving mastery',
    skills: [
      { title: 'Defensive driving principles', description: 'Anticipate, scan, plan ahead', teachingNotes: 'Scan 10 to 15 seconds ahead, ask what that car or pedestrian might do next, and already have an out. Assume others will miss a light or drift. Mastery is looking bored because you saw the problem early and were already slowing or changing lanes.' },
      { title: 'Identifying aggressive drivers', description: 'Avoid, don\'t engage, create distance', teachingNotes: 'Tailgating, weaving, and angry honks are your cue to let them go. Do not brake-check, stare, or match speed to “teach them.” Mastery is creating space and refusing the fight — their bad decision is not worth your record or your safety.' },
      { title: 'Distraction avoidance', description: 'Phone away, focus on road', teachingNotes: 'Phone down and out of reach before you shift into Drive. Eating, passengers, and the radio can wait if the road gets busy. Mastery is a cockpit that stays quiet — you never glance at a screen while the car is moving, even at a light.' },
      { title: 'Drowsy driving awareness', description: 'Signs of fatigue, when to stop', teachingNotes: 'Heavy eyelids, yawning, and missing a turn are stop signs. Open windows and loud music do not fix sleep. Mastery is pulling off to rest or calling for a ride the first time you notice it, not the third time you drift toward the line.' },
      { title: 'Road rage de-escalation', description: 'Stay calm, don\'t retaliate', teachingNotes: 'Do not make eye contact, do not gesture, and do not follow. Give them room and, if needed, drive to a public place or call 911. Mastery is walking away from the argument while you are still in the car — pride is not a driving skill.' },
      { title: 'Skid recovery', description: 'Steer into skid, don\'t overcorrect', teachingNotes: 'Ease off the gas and steer where you want the front of the car to go. Do not slam the brakes or yank the wheel the other way. Mastery is small, early steering that catches the slide before it becomes a spin.' },
      { title: 'Hydroplaning response', description: 'Ease off gas, steer straight', teachingNotes: 'If the steering goes light on standing water, ease off the gas and hold the wheel straight until the tires grab again. Do not brake hard or jerk. Mastery is already slower in heavy rain so hydroplaning is rare — and if it happens, you wait for grip instead of fighting the wheel.' },
      { title: 'Animal crossing response', description: 'Brake safely, don\'t swerve into traffic', teachingNotes: 'Brake firmly in your lane. Swerving into the next lane or the ditch is often worse than hitting a small animal. Mastery is a controlled stop or slow-down that keeps you on the pavement and away from oncoming cars, then hazards if you must stop.' },
      { title: 'Debris in road response', description: 'Assess, avoid safely, don\'t overreact', teachingNotes: 'If you can straddle it or change lanes with a check, do that. If not, slow in your lane. A last-second swerve at highway speed is the danger. Mastery is an early decision that looks calm from behind — no panic hop into someone else\'s path.' },
      { title: 'Accident scene response', description: 'Move to safety, call 911, document', teachingNotes: 'If you can, get out of the travel lanes, turn on hazards, check for injuries, and call 911. Exchange information; do not argue fault on the roadside. Mastery is safety first, then the legal steps, with photos when everyone is out of traffic.' },
      { title: 'Flat tire while driving', description: 'Grip wheel, slow gradually, pull over', teachingNotes: 'Hold the wheel, ease off the gas, and let the car slow before you work toward the shoulder. Hazards on. Mastery is a gradual move to a safe spot, not a sudden dive for the rumble strip that makes the car harder to control.' },
      { title: 'Car fire response', description: 'Pull over, exit, stay away, call 911', teachingNotes: 'Get off the road, stop, get everyone out and well away, then call 911. Do not open a smoking hood to “check.” Mastery is distance and a phone call — you do not stay beside a burning car to save belongings.' },
      { title: 'Navigating without GPS', description: 'Map reading, landmarks, asking directions', teachingNotes: 'Know the next two turns from a map or a sign before you need them. Landmarks beat staring at a phone. Mastery is being able to get home on posted routes, and pulling over to look something up instead of drifting across a lane while you pinch-zoom.' },
      { title: 'Parallel parking on hills', description: 'Curbing wheels, parking brake', teachingNotes: 'Park, then turn the wheels into the curb downhill, or away from the curb uphill, and set the parking brake hard. Confirm it does not roll. Mastery is a car that stays put if the transmission failed — the curb and the brake are doing the real work.' },
      { title: 'Towing awareness', description: 'Stopping distance, turning radius change', teachingNotes: 'A trailer needs more room to stop and a wider swing on turns. Brake earlier, take corners slower, and watch the trailer’s path in mirrors. Mastery is driving as if you are longer and heavier than you are, because you are.' },
    ],
  },
  {
    orderIndex: 8,
    title: 'Independent Driving Readiness',
    description: 'Real-world navigation and judgment',
    skills: [
      { title: 'Solo trip planning', description: 'Route selection, timing, alternatives', teachingNotes: 'Before you leave, know the route, a backup if a road is closed, and how long it really takes with traffic. Build extra time so you are not speeding to make it. Mastery is a plan on paper or in your head, not discovering the left turn you needed while you are already in the wrong lane.' },
      { title: 'Unfamiliar area navigation', description: 'GPS use, street signs, asking for help', teachingNotes: 'Set the destination before you move. Use signs to confirm the GPS, and pull over if you are lost. Mastery is staying in your lane while you navigate — if the screen and the road disagree, you choose a safe place to sort it out.' },
      { title: 'Parking in tight urban spaces', description: 'Judgment, patience, multiple attempts ok', teachingNotes: 'If it does not fit, find another spot. Go slow, take a second try, and protect bumpers and people walking behind you. Mastery is the decision to walk a little farther rather than forcing a space that will scrape or block someone in.' },
      { title: 'Drive-through navigation', description: 'Ordering, pulling forward, etiquette', teachingNotes: 'Stay in line, leave room to the car ahead, and pull forward to wait if they ask. Watch for pedestrians between the building and the cars. Mastery is a patient, predictable path through the lane with no rolling into the bumper in front of you while you talk.' },
      { title: 'Gas station operation', description: 'Fuel type, pump operation, payment', teachingNotes: 'Park by the correct pump, engine off, know regular versus the wrong fuel, then pump without walking away. Watch for traffic when you pull out. Mastery is a complete, unhurried fill that does not leave the nozzle in the car or pull out into a passing vehicle.' },
      { title: 'Car wash navigation', description: 'Automatic wash procedure', teachingNotes: 'Fold mirrors if needed, stay in Neutral or Drive as posted, hands off the wheel if they say so, and wait until you are fully out before you brake hard. Mastery is following the attendant and the lights so you do not tap the car ahead on the track.' },
      { title: 'Grocery store parking lot', description: 'Cart areas, pedestrian traffic', teachingNotes: 'Lots are full of people who are not looking. Drive slower than the street, yield to carts and kids, and park between the lines away from cart returns if you can. Mastery is treating the lot like a crowded crosswalk, not a shortcut to the door.' },
      { title: 'School pickup/dropoff zones', description: 'Rules, patience, watching for kids', teachingNotes: 'Follow the school’s lane rules, no passing stopped cars on the right, and assume a child will step out. Phone down. Mastery is a slow, legal line that never uses the bus lane or the crosswalk as a passing lane.' },
      { title: 'Highway rest stop usage', description: 'Entering, exiting, parking', teachingNotes: 'Signal into the rest area, slow on the ramp, park in a marked spot, and look before you back out. Re-enter the highway like any on-ramp: match speed, then merge. Mastery is using the stop to rest, then returning to traffic without a sudden stop at the end of the ramp.' },
      { title: 'Driving with passengers', description: 'Managing distractions from others', teachingNotes: 'You are still the driver. Ask friends to keep it down if you need quiet, and do not turn around to talk. Mastery is being willing to pull over to deal with chaos rather than driving through an argument or a phone being held in your face.' },
      { title: 'Night solo driving', description: 'Confidence and judgment alone at night', teachingNotes: 'Choose routes you know, keep following distance, and have a plan if you get tired or lost. Tell someone your route. Mastery is independent night driving that still looks conservative — you would make the same choices if an instructor were in the seat.' },
      { title: 'Extended trip (30+ min highway)', description: 'Fatigue management, comfort stops', teachingNotes: 'Set a pace you can hold, scan, and stop if you fade. Stretch, water, and a real break beat pushing the last twenty minutes. Mastery is finishing the trip as sharp as you started, because you scheduled rest instead of white-knuckling the last miles.' },
      { title: 'Bad weather solo driving', description: 'Independent decision to delay/stop', teachingNotes: 'You are allowed to wait out a storm or turn around. Ice, heavy snow, and zero visibility are not tests of courage. Mastery is the call to stay put — that decision is the skill, not making it through by luck.' },
      { title: 'Vehicle pre-trip inspection', description: 'Tires, lights, fluids check', teachingNotes: 'Walk around: tires look inflated, lights work, no leaks, windshield is clear, and you have enough fuel. Fix or delay if something is wrong. Mastery is a two-minute habit before every trip so you do not discover a problem at highway speed.' },
      { title: 'Missouri driver\'s test simulation', description: 'Pass full mock behind-wheel test', teachingNotes: 'Drive as if the examiner is scoring you: complete stops, legal lanes, proper signals, and calm gap choice. Narrate your checks if it helps. Mastery is a clean mock run you could repeat tomorrow — not a lucky day, a standard you already own.' },
    ],
  },
]

export function teachingNotesByTitle(): ReadonlyMap<string, string> {
  return new Map(
    trainingPhases.flatMap((phase) => phase.skills.map((skill) => [skill.title, skill.teachingNotes])),
  )
}
